package com.solace.connector.db.pull.entity;
// Generated 19-Sep-2023, 11:35:03 am by Hibernate Tools 5.6.2.Final


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="DEPARTMENT"
    
)
public class Department  implements java.io.Serializable {


     private BigDecimal departmentId;
     private Sector sector;
     private Employee employee;
     private String departmentName;

    public Department() {
    }

	
    public Department(BigDecimal departmentId, String departmentName) {
        this.departmentId = departmentId;
        this.departmentName = departmentName;
    }
    public Department(BigDecimal departmentId, Sector sector, Employee employee, String departmentName) {
       this.departmentId = departmentId;
       this.sector = sector;
       this.employee = employee;
       this.departmentName = departmentName;
    }
   
     @Id 

    
    @Column(name="DEPARTMENT_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(BigDecimal departmentId) {
        this.departmentId = departmentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYEE_ID")
    public Sector getSector() {
        return this.sector;
    }
    
    public void setSector(Sector sector) {
        this.sector = sector;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYEE_ID", insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="DEPARTMENT_NAME", nullable=false, length=200)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }




}


