package com.solace.connector.db.pull.entity;
// Generated 19-Sep-2023, 11:35:03 am by Hibernate Tools 5.6.2.Final


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="EMPLOYEE"
    
)
public class Employee  implements java.io.Serializable {


     private BigDecimal employeeId;
     private Students students;
     private String employeeName;
     private Set<Department> departments = new HashSet<Department>(0);

    public Employee() {
    }

	
    public Employee(Students students, String employeeName) {
        this.students = students;
        this.employeeName = employeeName;
    }
    public Employee(Students students, String employeeName, Set<Department> departments) {
       this.students = students;
       this.employeeName = employeeName;
       this.departments = departments;
    }
   
     @GenericGenerator(name="com.solace.connector.db.pull.entity.EmployeeIdGenerator", strategy="foreign", parameters=@Parameter(name="property", value="students"))@Id @GeneratedValue(generator="com.solace.connector.db.pull.entity.EmployeeIdGenerator")

    
    @Column(name="EMPLOYEE_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(BigDecimal employeeId) {
        this.employeeId = employeeId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }

    
    @Column(name="EMPLOYEE_NAME", nullable=false, length=50)
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sector")
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }




}


