package com.solace.connector.db.pull.entity;
// Generated 19-Sep-2023, 11:35:03 am by Hibernate Tools 5.6.2.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmployeesTest generated by hbm2java
 */
@Entity
@Table(name="EMPLOYEES_TEST"
    
    , uniqueConstraints = @UniqueConstraint(columnNames="EMAIL") 
)
public class EmployeesTest  implements java.io.Serializable {


     private BigDecimal employeeId;
     private String firstName;
     private String lastName;
     private String email;
     private Date hireDate;
     private BigDecimal salary;
     private BigDecimal departmentId;

    public EmployeesTest() {
    }

	
    public EmployeesTest(BigDecimal employeeId, String firstName, String lastName) {
        this.employeeId = employeeId;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public EmployeesTest(BigDecimal employeeId, String firstName, String lastName, String email, Date hireDate, BigDecimal salary, BigDecimal departmentId) {
       this.employeeId = employeeId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.hireDate = hireDate;
       this.salary = salary;
       this.departmentId = departmentId;
    }
   
     @Id 

    
    @Column(name="EMPLOYEE_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(BigDecimal employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="FIRST_NAME", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="EMAIL", unique=true, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="HIRE_DATE", length=7)
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    
    @Column(name="SALARY", precision=10)
    public BigDecimal getSalary() {
        return this.salary;
    }
    
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    
    @Column(name="DEPARTMENT_ID", precision=22, scale=0)
    public BigDecimal getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(BigDecimal departmentId) {
        this.departmentId = departmentId;
    }




}


