package com.solace.connector.db.pull.entity;
// Generated 19-Sep-2023, 11:35:03 am by Hibernate Tools 5.6.2.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MacsCountData generated by hbm2java
 */
@Entity
@Table(name="MACS_COUNT_DATA"
    
)
public class MacsCountData  implements java.io.Serializable {


     private MacsCountDataId id;

    public MacsCountData() {
    }

    public MacsCountData(MacsCountDataId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="mflId", column=@Column(name="MFL_ID", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="cntId", column=@Column(name="CNT_ID", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="fltSnapshotDay", column=@Column(name="FLT_SNAPSHOT_DAY", precision=2, scale=0) ), 
        @AttributeOverride(name="airlineDesignator", column=@Column(name="AIRLINE_DESIGNATOR", length=2) ), 
        @AttributeOverride(name="flightNumber", column=@Column(name="FLIGHT_NUMBER", length=4) ), 
        @AttributeOverride(name="fltScdDateTimeGmt", column=@Column(name="FLT_SCD_DATE_TIME_GMT", length=7) ), 
        @AttributeOverride(name="operationDate", column=@Column(name="OPERATION_DATE", length=7) ), 
        @AttributeOverride(name="operationTime", column=@Column(name="OPERATION_TIME", length=5) ), 
        @AttributeOverride(name="latestDepartureDate", column=@Column(name="LATEST_DEPARTURE_DATE", length=7) ), 
        @AttributeOverride(name="latestDepartureTime", column=@Column(name="LATEST_DEPARTURE_TIME", length=4) ), 
        @AttributeOverride(name="latestDepartureDateGmt", column=@Column(name="LATEST_DEPARTURE_DATE_GMT", length=7) ), 
        @AttributeOverride(name="latestDepartureTimeGmt", column=@Column(name="LATEST_DEPARTURE_TIME_GMT", length=4) ), 
        @AttributeOverride(name="latestArrivalDate", column=@Column(name="LATEST_ARRIVAL_DATE", length=7) ), 
        @AttributeOverride(name="latestArrivalTime", column=@Column(name="LATEST_ARRIVAL_TIME", length=4) ), 
        @AttributeOverride(name="latestArrivalDateGmt", column=@Column(name="LATEST_ARRIVAL_DATE_GMT", length=7) ), 
        @AttributeOverride(name="latestArrivalTimeGmt", column=@Column(name="LATEST_ARRIVAL_TIME_GMT", length=4) ), 
        @AttributeOverride(name="boardPoint", column=@Column(name="BOARD_POINT", length=3) ), 
        @AttributeOverride(name="destination", column=@Column(name="DESTINATION", length=3) ), 
        @AttributeOverride(name="registrationNumber", column=@Column(name="REGISTRATION_NUMBER", length=8) ), 
        @AttributeOverride(name="sequenceNo", column=@Column(name="SEQUENCE_NO", precision=2, scale=0) ), 
        @AttributeOverride(name="arrDeptrFlag", column=@Column(name="ARR_DEPTR_FLAG", length=2) ), 
        @AttributeOverride(name="classConfiguration", column=@Column(name="CLASS_CONFIGURATION", length=16) ), 
        @AttributeOverride(name="flightStatus", column=@Column(name="FLIGHT_STATUS", length=2) ), 
        @AttributeOverride(name="checkedInAdtPaxSecCountF", column=@Column(name="CHECKED_IN_ADT_PAX_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="checkedInAdtPaxBrdCountF", column=@Column(name="CHECKED_IN_ADT_PAX_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="checkedInAdtPaxSecCountJ", column=@Column(name="CHECKED_IN_ADT_PAX_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="checkedInAdtPaxBrdCountJ", column=@Column(name="CHECKED_IN_ADT_PAX_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="checkedInAdtPaxSecCountY", column=@Column(name="CHECKED_IN_ADT_PAX_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="checkedInAdtPaxBrdCountY", column=@Column(name="CHECKED_IN_ADT_PAX_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="checkedInChdPaxSecCountF", column=@Column(name="CHECKED_IN_CHD_PAX_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="checkedInChdPaxBrdCountF", column=@Column(name="CHECKED_IN_CHD_PAX_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="checkedInChdPaxSecCountJ", column=@Column(name="CHECKED_IN_CHD_PAX_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="checkedInChdPaxBrdCountJ", column=@Column(name="CHECKED_IN_CHD_PAX_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="checkedInChdPaxSecCountY", column=@Column(name="CHECKED_IN_CHD_PAX_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="checkedInChdPaxBrdCountY", column=@Column(name="CHECKED_IN_CHD_PAX_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="checkedInPaxSecCountF", column=@Column(name="CHECKED_IN_PAX_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="checkedInPaxBrdCountF", column=@Column(name="CHECKED_IN_PAX_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="checkedInPaxSecCountJ", column=@Column(name="CHECKED_IN_PAX_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="checkedInPaxBrdCountJ", column=@Column(name="CHECKED_IN_PAX_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="checkedInPaxSecCountY", column=@Column(name="CHECKED_IN_PAX_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="checkedInPaxBrdCountY", column=@Column(name="CHECKED_IN_PAX_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="checkedInInfantSecCountF", column=@Column(name="CHECKED_IN_INFANT_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="checkedInInfantBrdCountF", column=@Column(name="CHECKED_IN_INFANT_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="checkedInInfantSecCountJ", column=@Column(name="CHECKED_IN_INFANT_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="checkedInInfantBrdCountJ", column=@Column(name="CHECKED_IN_INFANT_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="checkedInInfantSecCountY", column=@Column(name="CHECKED_IN_INFANT_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="checkedInInfantBrdCountY", column=@Column(name="CHECKED_IN_INFANT_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="boardedAdtPaxSecCountF", column=@Column(name="BOARDED_ADT_PAX_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="boardedAdtPaxBrdCountF", column=@Column(name="BOARDED_ADT_PAX_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="boardedAdtPaxSecCountJ", column=@Column(name="BOARDED_ADT_PAX_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="boardedAdtPaxBrdCountJ", column=@Column(name="BOARDED_ADT_PAX_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="boardedAdtPaxSecCountY", column=@Column(name="BOARDED_ADT_PAX_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="boardedAdtPaxBrdCountY", column=@Column(name="BOARDED_ADT_PAX_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="boardedChdPaxSecCountF", column=@Column(name="BOARDED_CHD_PAX_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="boardedChdPaxBrdCountF", column=@Column(name="BOARDED_CHD_PAX_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="boardedChdPaxSecCountJ", column=@Column(name="BOARDED_CHD_PAX_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="boardedChdPaxBrdCountJ", column=@Column(name="BOARDED_CHD_PAX_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="boardedChdPaxSecCountY", column=@Column(name="BOARDED_CHD_PAX_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="boardedChdPaxBrdCountY", column=@Column(name="BOARDED_CHD_PAX_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="boardedPaxSecCountF", column=@Column(name="BOARDED_PAX_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="boardedPaxBrdCountF", column=@Column(name="BOARDED_PAX_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="boardedPaxSecCountJ", column=@Column(name="BOARDED_PAX_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="boardedPaxBrdCountJ", column=@Column(name="BOARDED_PAX_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="boardedPaxSecCountY", column=@Column(name="BOARDED_PAX_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="boardedPaxBrdCountY", column=@Column(name="BOARDED_PAX_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="boardedInfantSecCountF", column=@Column(name="BOARDED_INFANT_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="boardedInfantBrdCountF", column=@Column(name="BOARDED_INFANT_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="boardedInfantSecCountJ", column=@Column(name="BOARDED_INFANT_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="boardedInfantBrdCountJ", column=@Column(name="BOARDED_INFANT_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="boardedInfantSecCountY", column=@Column(name="BOARDED_INFANT_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="boardedInfantBrdCountY", column=@Column(name="BOARDED_INFANT_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="bookedAdtPaxSecCountF", column=@Column(name="BOOKED_ADT_PAX_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="bookedAdtPaxBrdCountF", column=@Column(name="BOOKED_ADT_PAX_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="bookedAdtPaxSecCountJ", column=@Column(name="BOOKED_ADT_PAX_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="bookedAdtPaxBrdCountJ", column=@Column(name="BOOKED_ADT_PAX_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="bookedAdtPaxSecCountY", column=@Column(name="BOOKED_ADT_PAX_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="bookedAdtPaxBrdCountY", column=@Column(name="BOOKED_ADT_PAX_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="bookedChdPaxSecCountF", column=@Column(name="BOOKED_CHD_PAX_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="bookedChdPaxBrdCountF", column=@Column(name="BOOKED_CHD_PAX_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="bookedChdPaxSecCountJ", column=@Column(name="BOOKED_CHD_PAX_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="bookedChdPaxBrdCountJ", column=@Column(name="BOOKED_CHD_PAX_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="bookedChdPaxSecCountY", column=@Column(name="BOOKED_CHD_PAX_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="bookedChdPaxBrdCountY", column=@Column(name="BOOKED_CHD_PAX_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="bookedPaxSecCountF", column=@Column(name="BOOKED_PAX_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="bookedPaxBrdCountF", column=@Column(name="BOOKED_PAX_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="bookedPaxSecCountJ", column=@Column(name="BOOKED_PAX_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="bookedPaxBrdCountJ", column=@Column(name="BOOKED_PAX_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="bookedPaxSecCountY", column=@Column(name="BOOKED_PAX_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="bookedPaxBrdCountY", column=@Column(name="BOOKED_PAX_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="bookedInfantSecCountF", column=@Column(name="BOOKED_INFANT_SEC_COUNT_F", length=6) ), 
        @AttributeOverride(name="bookedInfantBrdCountF", column=@Column(name="BOOKED_INFANT_BRD_COUNT_F", length=6) ), 
        @AttributeOverride(name="bookedInfantSecCountJ", column=@Column(name="BOOKED_INFANT_SEC_COUNT_J", length=6) ), 
        @AttributeOverride(name="bookedInfantBrdCountJ", column=@Column(name="BOOKED_INFANT_BRD_COUNT_J", length=6) ), 
        @AttributeOverride(name="bookedInfantSecCountY", column=@Column(name="BOOKED_INFANT_SEC_COUNT_Y", length=6) ), 
        @AttributeOverride(name="bookedInfantBrdCountY", column=@Column(name="BOOKED_INFANT_BRD_COUNT_Y", length=6) ), 
        @AttributeOverride(name="electronicTktCountSec", column=@Column(name="ELECTRONIC_TKT_COUNT_SEC", length=15) ), 
        @AttributeOverride(name="electronicTktCountBrd", column=@Column(name="ELECTRONIC_TKT_COUNT_BRD", length=15) ), 
        @AttributeOverride(name="boardingPassCountSec", column=@Column(name="BOARDING_PASS_COUNT_SEC", length=6) ), 
        @AttributeOverride(name="boardingPassCountBrd", column=@Column(name="BOARDING_PASS_COUNT_BRD", length=6) ), 
        @AttributeOverride(name="bagtagCountBrd", column=@Column(name="BAGTAG_COUNT_BRD", length=90) ), 
        @AttributeOverride(name="bagtagCountSec", column=@Column(name="BAGTAG_COUNT_SEC", length=90) ), 
        @AttributeOverride(name="arrivalPaxCount", column=@Column(name="ARRIVAL_PAX_COUNT", length=90) ), 
        @AttributeOverride(name="throughCheckedInCountBrd", column=@Column(name="THROUGH_CHECKED_IN_COUNT_BRD", length=60) ), 
        @AttributeOverride(name="throughCheckedInCountSec", column=@Column(name="THROUGH_CHECKED_IN_COUNT_SEC", length=60) ), 
        @AttributeOverride(name="tonnageBrd", column=@Column(name="TONNAGE_BRD", length=90) ), 
        @AttributeOverride(name="tonnageSec", column=@Column(name="TONNAGE_SEC", length=90) ), 
        @AttributeOverride(name="infTrnfDepInbCnt", column=@Column(name="INF_TRNF_DEP_INB_CNT", length=6) ), 
        @AttributeOverride(name="trnfDepInbCnt", column=@Column(name="TRNF_DEP_INB_CNT", length=6) ), 
        @AttributeOverride(name="trnfChdDepInbCnt", column=@Column(name="TRNF_CHD_DEP_INB_CNT", length=6) ), 
        @AttributeOverride(name="trnfDepInbCntF", column=@Column(name="TRNF_DEP_INB_CNT_F", length=6) ), 
        @AttributeOverride(name="trnfDepInbCntJ", column=@Column(name="TRNF_DEP_INB_CNT_J", length=6) ), 
        @AttributeOverride(name="trnfDepInbCntY", column=@Column(name="TRNF_DEP_INB_CNT_Y", length=6) ), 
        @AttributeOverride(name="infTrnfDesOnwCnt", column=@Column(name="INF_TRNF_DES_ONW_CNT", length=6) ), 
        @AttributeOverride(name="chdTrnfDesOnwCnt", column=@Column(name="CHD_TRNF_DES_ONW_CNT", length=6) ), 
        @AttributeOverride(name="trnfDesOnwCnt", column=@Column(name="TRNF_DES_ONW_CNT", length=6) ), 
        @AttributeOverride(name="trnfDesOnwCntF", column=@Column(name="TRNF_DES_ONW_CNT_F", length=6) ), 
        @AttributeOverride(name="trnfDesOnwCntJ", column=@Column(name="TRNF_DES_ONW_CNT_J", length=6) ), 
        @AttributeOverride(name="trnfDesOnwCntY", column=@Column(name="TRNF_DES_ONW_CNT_Y", length=6) ), 
        @AttributeOverride(name="transitCnt", column=@Column(name="TRANSIT_CNT", length=6) ), 
        @AttributeOverride(name="chdTransitCnt", column=@Column(name="CHD_TRANSIT_CNT", length=6) ), 
        @AttributeOverride(name="transitCntF", column=@Column(name="TRANSIT_CNT_F", length=6) ), 
        @AttributeOverride(name="transitCntJ", column=@Column(name="TRANSIT_CNT_J", length=6) ), 
        @AttributeOverride(name="transitCntY", column=@Column(name="TRANSIT_CNT_Y", length=6) ), 
        @AttributeOverride(name="bookedStaffCntF", column=@Column(name="BOOKED_STAFF_CNT_F", length=6) ), 
        @AttributeOverride(name="bookedStaffCntJ", column=@Column(name="BOOKED_STAFF_CNT_J", length=6) ), 
        @AttributeOverride(name="bookedStaffCntY", column=@Column(name="BOOKED_STAFF_CNT_Y", length=6) ), 
        @AttributeOverride(name="arrivalMultilegTrnfCntF", column=@Column(name="ARRIVAL_MULTILEG_TRNF_CNT_F", length=6) ), 
        @AttributeOverride(name="arrivalMultilegTrnfCntJ", column=@Column(name="ARRIVAL_MULTILEG_TRNF_CNT_J", length=6) ), 
        @AttributeOverride(name="arrivalMultilegTrnfCntY", column=@Column(name="ARRIVAL_MULTILEG_TRNF_CNT_Y", length=6) ), 
        @AttributeOverride(name="attribute1", column=@Column(name="ATTRIBUTE_1", length=6) ), 
        @AttributeOverride(name="attribute2", column=@Column(name="ATTRIBUTE_2", length=6) ), 
        @AttributeOverride(name="attribute3", column=@Column(name="ATTRIBUTE_3", length=6) ), 
        @AttributeOverride(name="attribute4", column=@Column(name="ATTRIBUTE_4", length=6) ), 
        @AttributeOverride(name="attribute5", column=@Column(name="ATTRIBUTE_5", length=6) ), 
        @AttributeOverride(name="attribute6", column=@Column(name="ATTRIBUTE_6", length=6) ), 
        @AttributeOverride(name="adbSequence", column=@Column(name="ADB_SEQUENCE", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="adbLDeliveryStatus", column=@Column(name="ADB_L_DELIVERY_STATUS", length=1) ), 
        @AttributeOverride(name="adbTimestamp", column=@Column(name="ADB_TIMESTAMP", length=7) ), 
        @AttributeOverride(name="adbOpcode", column=@Column(name="ADB_OPCODE", precision=22, scale=0) ), 
        @AttributeOverride(name="adbSetSequence", column=@Column(name="ADB_SET_SEQUENCE", precision=22, scale=0) ), 
        @AttributeOverride(name="adbLCmsequence", column=@Column(name="ADB_L_CMSEQUENCE", precision=22, scale=0) ), 
        @AttributeOverride(name="adbSubject", column=@Column(name="ADB_SUBJECT") ), 
        @AttributeOverride(name="adbUpdateAll", column=@Column(name="ADB_UPDATE_ALL", precision=22, scale=0) ), 
        @AttributeOverride(name="adbRefObject", column=@Column(name="ADB_REF_OBJECT", length=64) ), 
        @AttributeOverride(name="adbTrackingid", column=@Column(name="ADB_TRACKINGID", length=40) ), 
        @AttributeOverride(name="processStatus", column=@Column(name="PROCESS_STATUS", length=1) ), 
        @AttributeOverride(name="fnlArrTime", column=@Column(name="FNL_ARR_TIME", length=7) ), 
        @AttributeOverride(name="checkedInAdtPaxSecCountW", column=@Column(name="CHECKED_IN_ADT_PAX_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="checkedInAdtPaxBrdCountW", column=@Column(name="CHECKED_IN_ADT_PAX_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="checkedInChdPaxSecCountW", column=@Column(name="CHECKED_IN_CHD_PAX_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="checkedInChdPaxBrdCountW", column=@Column(name="CHECKED_IN_CHD_PAX_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="checkedInPaxSecCountW", column=@Column(name="CHECKED_IN_PAX_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="checkedInPaxBrdCountW", column=@Column(name="CHECKED_IN_PAX_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="checkedInInfantSecCountW", column=@Column(name="CHECKED_IN_INFANT_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="checkedInInfantBrdCountW", column=@Column(name="CHECKED_IN_INFANT_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="boardedAdtPaxSecCountW", column=@Column(name="BOARDED_ADT_PAX_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="boardedAdtPaxBrdCountW", column=@Column(name="BOARDED_ADT_PAX_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="boardedChdPaxSecCountW", column=@Column(name="BOARDED_CHD_PAX_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="boardedChdPaxBrdCountW", column=@Column(name="BOARDED_CHD_PAX_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="boardedPaxSecCountW", column=@Column(name="BOARDED_PAX_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="boardedPaxBrdCountW", column=@Column(name="BOARDED_PAX_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="boardedInfantSecCountW", column=@Column(name="BOARDED_INFANT_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="boardedInfantBrdCountW", column=@Column(name="BOARDED_INFANT_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="bookedAdtPaxSecCountW", column=@Column(name="BOOKED_ADT_PAX_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="bookedAdtPaxBrdCountW", column=@Column(name="BOOKED_ADT_PAX_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="bookedChdPaxSecCountW", column=@Column(name="BOOKED_CHD_PAX_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="bookedChdPaxBrdCountW", column=@Column(name="BOOKED_CHD_PAX_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="bookedPaxSecCountW", column=@Column(name="BOOKED_PAX_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="bookedPaxBrdCountW", column=@Column(name="BOOKED_PAX_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="bookedInfantSecCountW", column=@Column(name="BOOKED_INFANT_SEC_COUNT_W", length=6) ), 
        @AttributeOverride(name="bookedInfantBrdCountW", column=@Column(name="BOOKED_INFANT_BRD_COUNT_W", length=6) ), 
        @AttributeOverride(name="trnfDepInbCntW", column=@Column(name="TRNF_DEP_INB_CNT_W", length=6) ), 
        @AttributeOverride(name="trnfDesOnwCntW", column=@Column(name="TRNF_DES_ONW_CNT_W", length=6) ), 
        @AttributeOverride(name="transitCntW", column=@Column(name="TRANSIT_CNT_W", length=6) ), 
        @AttributeOverride(name="bookedStaffCntW", column=@Column(name="BOOKED_STAFF_CNT_W", length=6) ), 
        @AttributeOverride(name="arrivalMultilegTrnfCntW", column=@Column(name="ARRIVAL_MULTILEG_TRNF_CNT_W", length=6) ) } )
    public MacsCountDataId getId() {
        return this.id;
    }
    
    public void setId(MacsCountDataId id) {
        this.id = id;
    }




}


