package com.solace.connector.db.pull.entity;
// Generated 19-Sep-2023, 11:35:03 am by Hibernate Tools 5.6.2.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PassAddress generated by hbm2java
 */
@Entity
@Table(name="PASS_ADDRESS"
    
)
public class PassAddress  implements java.io.Serializable {


     private PassAddressId id;

    public PassAddress() {
    }

    public PassAddress(PassAddressId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="city", column=@Column(name="CITY") ), 
        @AttributeOverride(name="zip", column=@Column(name="ZIP") ), 
        @AttributeOverride(name="passId", column=@Column(name="PASS_ID", precision=10, scale=0) ) } )
    public PassAddressId getId() {
        return this.id;
    }
    
    public void setId(PassAddressId id) {
        this.id = id;
    }




}


