package com.solace.connector.db.pull.entity;
// Generated 19-Sep-2023, 11:35:03 am by Hibernate Tools 5.6.2.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PMacsTbc7Flt generated by hbm2java
 */
@Entity
@Table(name="P_MACS_TBC_7_FLT"
    
)
public class PMacsTbc7Flt  implements java.io.Serializable {


     private PMacsTbc7FltId id;

    public PMacsTbc7Flt() {
    }

    public PMacsTbc7Flt(PMacsTbc7FltId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fltSnapshotDay", column=@Column(name="FLT_SNAPSHOT_DAY", precision=2, scale=0) ), 
        @AttributeOverride(name="fltSeq", column=@Column(name="FLT_SEQ", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="mflId", column=@Column(name="MFL_ID", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="airlineDesignator", column=@Column(name="AIRLINE_DESIGNATOR", length=2) ), 
        @AttributeOverride(name="airlineDesignatorExp", column=@Column(name="AIRLINE_DESIGNATOR_EXP", length=1) ), 
        @AttributeOverride(name="flightNumber", column=@Column(name="FLIGHT_NUMBER", length=4) ), 
        @AttributeOverride(name="operationDate", column=@Column(name="OPERATION_DATE", length=7) ), 
        @AttributeOverride(name="operationTime", column=@Column(name="OPERATION_TIME", length=4) ), 
        @AttributeOverride(name="operationDateGmt", column=@Column(name="OPERATION_DATE_GMT", length=7) ), 
        @AttributeOverride(name="operationTimeGmt", column=@Column(name="OPERATION_TIME_GMT", length=4) ), 
        @AttributeOverride(name="latestDepartureDate", column=@Column(name="LATEST_DEPARTURE_DATE", length=7) ), 
        @AttributeOverride(name="latestDepartureTime", column=@Column(name="LATEST_DEPARTURE_TIME", length=4) ), 
        @AttributeOverride(name="latestDepartureDateGmt", column=@Column(name="LATEST_DEPARTURE_DATE_GMT", length=7) ), 
        @AttributeOverride(name="latestDepartureTimeGmt", column=@Column(name="LATEST_DEPARTURE_TIME_GMT", length=4) ), 
        @AttributeOverride(name="boardPoint", column=@Column(name="BOARD_POINT", length=3) ), 
        @AttributeOverride(name="aircraftType", column=@Column(name="AIRCRAFT_TYPE", length=3) ), 
        @AttributeOverride(name="classConfiguration", column=@Column(name="CLASS_CONFIGURATION", length=16) ), 
        @AttributeOverride(name="registrationNumber", column=@Column(name="REGISTRATION_NUMBER", length=8) ), 
        @AttributeOverride(name="pantryCode", column=@Column(name="PANTRY_CODE", length=1) ), 
        @AttributeOverride(name="crewCode", column=@Column(name="CREW_CODE", length=1) ), 
        @AttributeOverride(name="gateNumber", column=@Column(name="GATE_NUMBER", length=4) ), 
        @AttributeOverride(name="baggageConcept", column=@Column(name="BAGGAGE_CONCEPT", length=3) ), 
        @AttributeOverride(name="seatMaskCode", column=@Column(name="SEAT_MASK_CODE", precision=1, scale=0) ), 
        @AttributeOverride(name="uldCode", column=@Column(name="ULD_CODE", length=3) ), 
        @AttributeOverride(name="flightStatus", column=@Column(name="FLIGHT_STATUS", length=2) ), 
        @AttributeOverride(name="progress", column=@Column(name="PROGRESS", length=1) ), 
        @AttributeOverride(name="downloadDate", column=@Column(name="DOWNLOAD_DATE", length=7) ), 
        @AttributeOverride(name="timeStamp", column=@Column(name="TIME_STAMP", precision=6, scale=0) ), 
        @AttributeOverride(name="flightNumberExp", column=@Column(name="FLIGHT_NUMBER_EXP", length=1) ), 
        @AttributeOverride(name="created", column=@Column(name="CREATED", length=7) ), 
        @AttributeOverride(name="usrCreated", column=@Column(name="USR_CREATED", length=30) ), 
        @AttributeOverride(name="changed", column=@Column(name="CHANGED", length=7) ), 
        @AttributeOverride(name="usrChanged", column=@Column(name="USR_CHANGED", length=30) ), 
        @AttributeOverride(name="ffNotified", column=@Column(name="FF_NOTIFIED", length=1) ), 
        @AttributeOverride(name="pdCount", column=@Column(name="PD_COUNT", precision=22, scale=0) ), 
        @AttributeOverride(name="status", column=@Column(name="STATUS", length=2) ), 
        @AttributeOverride(name="scheduledDate", column=@Column(name="SCHEDULED_DATE", length=7) ), 
        @AttributeOverride(name="arrDepFlag", column=@Column(name="ARR_DEP_FLAG", length=1) ), 
        @AttributeOverride(name="createdDate", column=@Column(name="CREATED_DATE", length=7) ), 
        @AttributeOverride(name="dmlFlag", column=@Column(name="DML_FLAG", length=1) ), 
        @AttributeOverride(name="adbSubject", column=@Column(name="ADB_SUBJECT") ), 
        @AttributeOverride(name="adbSequence", column=@Column(name="ADB_SEQUENCE", nullable=false, precision=38, scale=0) ), 
        @AttributeOverride(name="adbSetSequence", column=@Column(name="ADB_SET_SEQUENCE", precision=38, scale=0) ), 
        @AttributeOverride(name="adbTimestamp", column=@Column(name="ADB_TIMESTAMP", length=13) ), 
        @AttributeOverride(name="adbOpcode", column=@Column(name="ADB_OPCODE", nullable=false, precision=38, scale=0) ), 
        @AttributeOverride(name="adbUpdateAll", column=@Column(name="ADB_UPDATE_ALL", precision=38, scale=0) ), 
        @AttributeOverride(name="adbRefObject", column=@Column(name="ADB_REF_OBJECT", length=64) ), 
        @AttributeOverride(name="adbLDeliveryStatus", column=@Column(name="ADB_L_DELIVERY_STATUS", length=1) ), 
        @AttributeOverride(name="adbLCmsequence", column=@Column(name="ADB_L_CMSEQUENCE", precision=38, scale=0) ), 
        @AttributeOverride(name="adbTrackingid", column=@Column(name="ADB_TRACKINGID", length=40) ) } )
    public PMacsTbc7FltId getId() {
        return this.id;
    }
    
    public void setId(PMacsTbc7FltId id) {
        this.id = id;
    }




}


