package com.solace.connector.db.pull.entity;
// Generated 19-Sep-2023, 11:35:03 am by Hibernate Tools 5.6.2.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PMacsTbc7FltId generated by hbm2java
 */
@Embeddable
public class PMacsTbc7FltId  implements java.io.Serializable {


     private BigDecimal fltSnapshotDay;
     private BigDecimal fltSeq;
     private BigDecimal mflId;
     private String airlineDesignator;
     private String airlineDesignatorExp;
     private String flightNumber;
     private Date operationDate;
     private String operationTime;
     private Date operationDateGmt;
     private String operationTimeGmt;
     private Date latestDepartureDate;
     private String latestDepartureTime;
     private Date latestDepartureDateGmt;
     private String latestDepartureTimeGmt;
     private String boardPoint;
     private String aircraftType;
     private String classConfiguration;
     private String registrationNumber;
     private String pantryCode;
     private String crewCode;
     private String gateNumber;
     private String baggageConcept;
     private BigDecimal seatMaskCode;
     private String uldCode;
     private String flightStatus;
     private String progress;
     private Date downloadDate;
     private BigDecimal timeStamp;
     private String flightNumberExp;
     private Date created;
     private String usrCreated;
     private Date changed;
     private String usrChanged;
     private String ffNotified;
     private BigDecimal pdCount;
     private String status;
     private Date scheduledDate;
     private String arrDepFlag;
     private Date createdDate;
     private String dmlFlag;
     private String adbSubject;
     private BigDecimal adbSequence;
     private BigDecimal adbSetSequence;
     private Date adbTimestamp;
     private BigDecimal adbOpcode;
     private BigDecimal adbUpdateAll;
     private String adbRefObject;
     private Character adbLDeliveryStatus;
     private BigDecimal adbLCmsequence;
     private String adbTrackingid;

    public PMacsTbc7FltId() {
    }

	
    public PMacsTbc7FltId(BigDecimal fltSeq, BigDecimal mflId, BigDecimal adbSequence, BigDecimal adbOpcode) {
        this.fltSeq = fltSeq;
        this.mflId = mflId;
        this.adbSequence = adbSequence;
        this.adbOpcode = adbOpcode;
    }
    public PMacsTbc7FltId(BigDecimal fltSnapshotDay, BigDecimal fltSeq, BigDecimal mflId, String airlineDesignator, String airlineDesignatorExp, String flightNumber, Date operationDate, String operationTime, Date operationDateGmt, String operationTimeGmt, Date latestDepartureDate, String latestDepartureTime, Date latestDepartureDateGmt, String latestDepartureTimeGmt, String boardPoint, String aircraftType, String classConfiguration, String registrationNumber, String pantryCode, String crewCode, String gateNumber, String baggageConcept, BigDecimal seatMaskCode, String uldCode, String flightStatus, String progress, Date downloadDate, BigDecimal timeStamp, String flightNumberExp, Date created, String usrCreated, Date changed, String usrChanged, String ffNotified, BigDecimal pdCount, String status, Date scheduledDate, String arrDepFlag, Date createdDate, String dmlFlag, String adbSubject, BigDecimal adbSequence, BigDecimal adbSetSequence, Date adbTimestamp, BigDecimal adbOpcode, BigDecimal adbUpdateAll, String adbRefObject, Character adbLDeliveryStatus, BigDecimal adbLCmsequence, String adbTrackingid) {
       this.fltSnapshotDay = fltSnapshotDay;
       this.fltSeq = fltSeq;
       this.mflId = mflId;
       this.airlineDesignator = airlineDesignator;
       this.airlineDesignatorExp = airlineDesignatorExp;
       this.flightNumber = flightNumber;
       this.operationDate = operationDate;
       this.operationTime = operationTime;
       this.operationDateGmt = operationDateGmt;
       this.operationTimeGmt = operationTimeGmt;
       this.latestDepartureDate = latestDepartureDate;
       this.latestDepartureTime = latestDepartureTime;
       this.latestDepartureDateGmt = latestDepartureDateGmt;
       this.latestDepartureTimeGmt = latestDepartureTimeGmt;
       this.boardPoint = boardPoint;
       this.aircraftType = aircraftType;
       this.classConfiguration = classConfiguration;
       this.registrationNumber = registrationNumber;
       this.pantryCode = pantryCode;
       this.crewCode = crewCode;
       this.gateNumber = gateNumber;
       this.baggageConcept = baggageConcept;
       this.seatMaskCode = seatMaskCode;
       this.uldCode = uldCode;
       this.flightStatus = flightStatus;
       this.progress = progress;
       this.downloadDate = downloadDate;
       this.timeStamp = timeStamp;
       this.flightNumberExp = flightNumberExp;
       this.created = created;
       this.usrCreated = usrCreated;
       this.changed = changed;
       this.usrChanged = usrChanged;
       this.ffNotified = ffNotified;
       this.pdCount = pdCount;
       this.status = status;
       this.scheduledDate = scheduledDate;
       this.arrDepFlag = arrDepFlag;
       this.createdDate = createdDate;
       this.dmlFlag = dmlFlag;
       this.adbSubject = adbSubject;
       this.adbSequence = adbSequence;
       this.adbSetSequence = adbSetSequence;
       this.adbTimestamp = adbTimestamp;
       this.adbOpcode = adbOpcode;
       this.adbUpdateAll = adbUpdateAll;
       this.adbRefObject = adbRefObject;
       this.adbLDeliveryStatus = adbLDeliveryStatus;
       this.adbLCmsequence = adbLCmsequence;
       this.adbTrackingid = adbTrackingid;
    }
   


    @Column(name="FLT_SNAPSHOT_DAY", precision=2, scale=0)
    public BigDecimal getFltSnapshotDay() {
        return this.fltSnapshotDay;
    }
    
    public void setFltSnapshotDay(BigDecimal fltSnapshotDay) {
        this.fltSnapshotDay = fltSnapshotDay;
    }


    @Column(name="FLT_SEQ", nullable=false, precision=12, scale=0)
    public BigDecimal getFltSeq() {
        return this.fltSeq;
    }
    
    public void setFltSeq(BigDecimal fltSeq) {
        this.fltSeq = fltSeq;
    }


    @Column(name="MFL_ID", nullable=false, precision=8, scale=0)
    public BigDecimal getMflId() {
        return this.mflId;
    }
    
    public void setMflId(BigDecimal mflId) {
        this.mflId = mflId;
    }


    @Column(name="AIRLINE_DESIGNATOR", length=2)
    public String getAirlineDesignator() {
        return this.airlineDesignator;
    }
    
    public void setAirlineDesignator(String airlineDesignator) {
        this.airlineDesignator = airlineDesignator;
    }


    @Column(name="AIRLINE_DESIGNATOR_EXP", length=1)
    public String getAirlineDesignatorExp() {
        return this.airlineDesignatorExp;
    }
    
    public void setAirlineDesignatorExp(String airlineDesignatorExp) {
        this.airlineDesignatorExp = airlineDesignatorExp;
    }


    @Column(name="FLIGHT_NUMBER", length=4)
    public String getFlightNumber() {
        return this.flightNumber;
    }
    
    public void setFlightNumber(String flightNumber) {
        this.flightNumber = flightNumber;
    }


    @Column(name="OPERATION_DATE", length=7)
    public Date getOperationDate() {
        return this.operationDate;
    }
    
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }


    @Column(name="OPERATION_TIME", length=4)
    public String getOperationTime() {
        return this.operationTime;
    }
    
    public void setOperationTime(String operationTime) {
        this.operationTime = operationTime;
    }


    @Column(name="OPERATION_DATE_GMT", length=7)
    public Date getOperationDateGmt() {
        return this.operationDateGmt;
    }
    
    public void setOperationDateGmt(Date operationDateGmt) {
        this.operationDateGmt = operationDateGmt;
    }


    @Column(name="OPERATION_TIME_GMT", length=4)
    public String getOperationTimeGmt() {
        return this.operationTimeGmt;
    }
    
    public void setOperationTimeGmt(String operationTimeGmt) {
        this.operationTimeGmt = operationTimeGmt;
    }


    @Column(name="LATEST_DEPARTURE_DATE", length=7)
    public Date getLatestDepartureDate() {
        return this.latestDepartureDate;
    }
    
    public void setLatestDepartureDate(Date latestDepartureDate) {
        this.latestDepartureDate = latestDepartureDate;
    }


    @Column(name="LATEST_DEPARTURE_TIME", length=4)
    public String getLatestDepartureTime() {
        return this.latestDepartureTime;
    }
    
    public void setLatestDepartureTime(String latestDepartureTime) {
        this.latestDepartureTime = latestDepartureTime;
    }


    @Column(name="LATEST_DEPARTURE_DATE_GMT", length=7)
    public Date getLatestDepartureDateGmt() {
        return this.latestDepartureDateGmt;
    }
    
    public void setLatestDepartureDateGmt(Date latestDepartureDateGmt) {
        this.latestDepartureDateGmt = latestDepartureDateGmt;
    }


    @Column(name="LATEST_DEPARTURE_TIME_GMT", length=4)
    public String getLatestDepartureTimeGmt() {
        return this.latestDepartureTimeGmt;
    }
    
    public void setLatestDepartureTimeGmt(String latestDepartureTimeGmt) {
        this.latestDepartureTimeGmt = latestDepartureTimeGmt;
    }


    @Column(name="BOARD_POINT", length=3)
    public String getBoardPoint() {
        return this.boardPoint;
    }
    
    public void setBoardPoint(String boardPoint) {
        this.boardPoint = boardPoint;
    }


    @Column(name="AIRCRAFT_TYPE", length=3)
    public String getAircraftType() {
        return this.aircraftType;
    }
    
    public void setAircraftType(String aircraftType) {
        this.aircraftType = aircraftType;
    }


    @Column(name="CLASS_CONFIGURATION", length=16)
    public String getClassConfiguration() {
        return this.classConfiguration;
    }
    
    public void setClassConfiguration(String classConfiguration) {
        this.classConfiguration = classConfiguration;
    }


    @Column(name="REGISTRATION_NUMBER", length=8)
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }
    
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }


    @Column(name="PANTRY_CODE", length=1)
    public String getPantryCode() {
        return this.pantryCode;
    }
    
    public void setPantryCode(String pantryCode) {
        this.pantryCode = pantryCode;
    }


    @Column(name="CREW_CODE", length=1)
    public String getCrewCode() {
        return this.crewCode;
    }
    
    public void setCrewCode(String crewCode) {
        this.crewCode = crewCode;
    }


    @Column(name="GATE_NUMBER", length=4)
    public String getGateNumber() {
        return this.gateNumber;
    }
    
    public void setGateNumber(String gateNumber) {
        this.gateNumber = gateNumber;
    }


    @Column(name="BAGGAGE_CONCEPT", length=3)
    public String getBaggageConcept() {
        return this.baggageConcept;
    }
    
    public void setBaggageConcept(String baggageConcept) {
        this.baggageConcept = baggageConcept;
    }


    @Column(name="SEAT_MASK_CODE", precision=1, scale=0)
    public BigDecimal getSeatMaskCode() {
        return this.seatMaskCode;
    }
    
    public void setSeatMaskCode(BigDecimal seatMaskCode) {
        this.seatMaskCode = seatMaskCode;
    }


    @Column(name="ULD_CODE", length=3)
    public String getUldCode() {
        return this.uldCode;
    }
    
    public void setUldCode(String uldCode) {
        this.uldCode = uldCode;
    }


    @Column(name="FLIGHT_STATUS", length=2)
    public String getFlightStatus() {
        return this.flightStatus;
    }
    
    public void setFlightStatus(String flightStatus) {
        this.flightStatus = flightStatus;
    }


    @Column(name="PROGRESS", length=1)
    public String getProgress() {
        return this.progress;
    }
    
    public void setProgress(String progress) {
        this.progress = progress;
    }


    @Column(name="DOWNLOAD_DATE", length=7)
    public Date getDownloadDate() {
        return this.downloadDate;
    }
    
    public void setDownloadDate(Date downloadDate) {
        this.downloadDate = downloadDate;
    }


    @Column(name="TIME_STAMP", precision=6, scale=0)
    public BigDecimal getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(BigDecimal timeStamp) {
        this.timeStamp = timeStamp;
    }


    @Column(name="FLIGHT_NUMBER_EXP", length=1)
    public String getFlightNumberExp() {
        return this.flightNumberExp;
    }
    
    public void setFlightNumberExp(String flightNumberExp) {
        this.flightNumberExp = flightNumberExp;
    }


    @Column(name="CREATED", length=7)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }


    @Column(name="USR_CREATED", length=30)
    public String getUsrCreated() {
        return this.usrCreated;
    }
    
    public void setUsrCreated(String usrCreated) {
        this.usrCreated = usrCreated;
    }


    @Column(name="CHANGED", length=7)
    public Date getChanged() {
        return this.changed;
    }
    
    public void setChanged(Date changed) {
        this.changed = changed;
    }


    @Column(name="USR_CHANGED", length=30)
    public String getUsrChanged() {
        return this.usrChanged;
    }
    
    public void setUsrChanged(String usrChanged) {
        this.usrChanged = usrChanged;
    }


    @Column(name="FF_NOTIFIED", length=1)
    public String getFfNotified() {
        return this.ffNotified;
    }
    
    public void setFfNotified(String ffNotified) {
        this.ffNotified = ffNotified;
    }


    @Column(name="PD_COUNT", precision=22, scale=0)
    public BigDecimal getPdCount() {
        return this.pdCount;
    }
    
    public void setPdCount(BigDecimal pdCount) {
        this.pdCount = pdCount;
    }


    @Column(name="STATUS", length=2)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }


    @Column(name="SCHEDULED_DATE", length=7)
    public Date getScheduledDate() {
        return this.scheduledDate;
    }
    
    public void setScheduledDate(Date scheduledDate) {
        this.scheduledDate = scheduledDate;
    }


    @Column(name="ARR_DEP_FLAG", length=1)
    public String getArrDepFlag() {
        return this.arrDepFlag;
    }
    
    public void setArrDepFlag(String arrDepFlag) {
        this.arrDepFlag = arrDepFlag;
    }


    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }


    @Column(name="DML_FLAG", length=1)
    public String getDmlFlag() {
        return this.dmlFlag;
    }
    
    public void setDmlFlag(String dmlFlag) {
        this.dmlFlag = dmlFlag;
    }


    @Column(name="ADB_SUBJECT")
    public String getAdbSubject() {
        return this.adbSubject;
    }
    
    public void setAdbSubject(String adbSubject) {
        this.adbSubject = adbSubject;
    }


    @Column(name="ADB_SEQUENCE", nullable=false, precision=38, scale=0)
    public BigDecimal getAdbSequence() {
        return this.adbSequence;
    }
    
    public void setAdbSequence(BigDecimal adbSequence) {
        this.adbSequence = adbSequence;
    }


    @Column(name="ADB_SET_SEQUENCE", precision=38, scale=0)
    public BigDecimal getAdbSetSequence() {
        return this.adbSetSequence;
    }
    
    public void setAdbSetSequence(BigDecimal adbSetSequence) {
        this.adbSetSequence = adbSetSequence;
    }


    @Column(name="ADB_TIMESTAMP", length=13)
    public Date getAdbTimestamp() {
        return this.adbTimestamp;
    }
    
    public void setAdbTimestamp(Date adbTimestamp) {
        this.adbTimestamp = adbTimestamp;
    }


    @Column(name="ADB_OPCODE", nullable=false, precision=38, scale=0)
    public BigDecimal getAdbOpcode() {
        return this.adbOpcode;
    }
    
    public void setAdbOpcode(BigDecimal adbOpcode) {
        this.adbOpcode = adbOpcode;
    }


    @Column(name="ADB_UPDATE_ALL", precision=38, scale=0)
    public BigDecimal getAdbUpdateAll() {
        return this.adbUpdateAll;
    }
    
    public void setAdbUpdateAll(BigDecimal adbUpdateAll) {
        this.adbUpdateAll = adbUpdateAll;
    }


    @Column(name="ADB_REF_OBJECT", length=64)
    public String getAdbRefObject() {
        return this.adbRefObject;
    }
    
    public void setAdbRefObject(String adbRefObject) {
        this.adbRefObject = adbRefObject;
    }


    @Column(name="ADB_L_DELIVERY_STATUS", length=1)
    public Character getAdbLDeliveryStatus() {
        return this.adbLDeliveryStatus;
    }
    
    public void setAdbLDeliveryStatus(Character adbLDeliveryStatus) {
        this.adbLDeliveryStatus = adbLDeliveryStatus;
    }


    @Column(name="ADB_L_CMSEQUENCE", precision=38, scale=0)
    public BigDecimal getAdbLCmsequence() {
        return this.adbLCmsequence;
    }
    
    public void setAdbLCmsequence(BigDecimal adbLCmsequence) {
        this.adbLCmsequence = adbLCmsequence;
    }


    @Column(name="ADB_TRACKINGID", length=40)
    public String getAdbTrackingid() {
        return this.adbTrackingid;
    }
    
    public void setAdbTrackingid(String adbTrackingid) {
        this.adbTrackingid = adbTrackingid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PMacsTbc7FltId) ) return false;
		 PMacsTbc7FltId castOther = ( PMacsTbc7FltId ) other; 
         
		 return ( (this.getFltSnapshotDay()==castOther.getFltSnapshotDay()) || ( this.getFltSnapshotDay()!=null && castOther.getFltSnapshotDay()!=null && this.getFltSnapshotDay().equals(castOther.getFltSnapshotDay()) ) )
 && ( (this.getFltSeq()==castOther.getFltSeq()) || ( this.getFltSeq()!=null && castOther.getFltSeq()!=null && this.getFltSeq().equals(castOther.getFltSeq()) ) )
 && ( (this.getMflId()==castOther.getMflId()) || ( this.getMflId()!=null && castOther.getMflId()!=null && this.getMflId().equals(castOther.getMflId()) ) )
 && ( (this.getAirlineDesignator()==castOther.getAirlineDesignator()) || ( this.getAirlineDesignator()!=null && castOther.getAirlineDesignator()!=null && this.getAirlineDesignator().equals(castOther.getAirlineDesignator()) ) )
 && ( (this.getAirlineDesignatorExp()==castOther.getAirlineDesignatorExp()) || ( this.getAirlineDesignatorExp()!=null && castOther.getAirlineDesignatorExp()!=null && this.getAirlineDesignatorExp().equals(castOther.getAirlineDesignatorExp()) ) )
 && ( (this.getFlightNumber()==castOther.getFlightNumber()) || ( this.getFlightNumber()!=null && castOther.getFlightNumber()!=null && this.getFlightNumber().equals(castOther.getFlightNumber()) ) )
 && ( (this.getOperationDate()==castOther.getOperationDate()) || ( this.getOperationDate()!=null && castOther.getOperationDate()!=null && this.getOperationDate().equals(castOther.getOperationDate()) ) )
 && ( (this.getOperationTime()==castOther.getOperationTime()) || ( this.getOperationTime()!=null && castOther.getOperationTime()!=null && this.getOperationTime().equals(castOther.getOperationTime()) ) )
 && ( (this.getOperationDateGmt()==castOther.getOperationDateGmt()) || ( this.getOperationDateGmt()!=null && castOther.getOperationDateGmt()!=null && this.getOperationDateGmt().equals(castOther.getOperationDateGmt()) ) )
 && ( (this.getOperationTimeGmt()==castOther.getOperationTimeGmt()) || ( this.getOperationTimeGmt()!=null && castOther.getOperationTimeGmt()!=null && this.getOperationTimeGmt().equals(castOther.getOperationTimeGmt()) ) )
 && ( (this.getLatestDepartureDate()==castOther.getLatestDepartureDate()) || ( this.getLatestDepartureDate()!=null && castOther.getLatestDepartureDate()!=null && this.getLatestDepartureDate().equals(castOther.getLatestDepartureDate()) ) )
 && ( (this.getLatestDepartureTime()==castOther.getLatestDepartureTime()) || ( this.getLatestDepartureTime()!=null && castOther.getLatestDepartureTime()!=null && this.getLatestDepartureTime().equals(castOther.getLatestDepartureTime()) ) )
 && ( (this.getLatestDepartureDateGmt()==castOther.getLatestDepartureDateGmt()) || ( this.getLatestDepartureDateGmt()!=null && castOther.getLatestDepartureDateGmt()!=null && this.getLatestDepartureDateGmt().equals(castOther.getLatestDepartureDateGmt()) ) )
 && ( (this.getLatestDepartureTimeGmt()==castOther.getLatestDepartureTimeGmt()) || ( this.getLatestDepartureTimeGmt()!=null && castOther.getLatestDepartureTimeGmt()!=null && this.getLatestDepartureTimeGmt().equals(castOther.getLatestDepartureTimeGmt()) ) )
 && ( (this.getBoardPoint()==castOther.getBoardPoint()) || ( this.getBoardPoint()!=null && castOther.getBoardPoint()!=null && this.getBoardPoint().equals(castOther.getBoardPoint()) ) )
 && ( (this.getAircraftType()==castOther.getAircraftType()) || ( this.getAircraftType()!=null && castOther.getAircraftType()!=null && this.getAircraftType().equals(castOther.getAircraftType()) ) )
 && ( (this.getClassConfiguration()==castOther.getClassConfiguration()) || ( this.getClassConfiguration()!=null && castOther.getClassConfiguration()!=null && this.getClassConfiguration().equals(castOther.getClassConfiguration()) ) )
 && ( (this.getRegistrationNumber()==castOther.getRegistrationNumber()) || ( this.getRegistrationNumber()!=null && castOther.getRegistrationNumber()!=null && this.getRegistrationNumber().equals(castOther.getRegistrationNumber()) ) )
 && ( (this.getPantryCode()==castOther.getPantryCode()) || ( this.getPantryCode()!=null && castOther.getPantryCode()!=null && this.getPantryCode().equals(castOther.getPantryCode()) ) )
 && ( (this.getCrewCode()==castOther.getCrewCode()) || ( this.getCrewCode()!=null && castOther.getCrewCode()!=null && this.getCrewCode().equals(castOther.getCrewCode()) ) )
 && ( (this.getGateNumber()==castOther.getGateNumber()) || ( this.getGateNumber()!=null && castOther.getGateNumber()!=null && this.getGateNumber().equals(castOther.getGateNumber()) ) )
 && ( (this.getBaggageConcept()==castOther.getBaggageConcept()) || ( this.getBaggageConcept()!=null && castOther.getBaggageConcept()!=null && this.getBaggageConcept().equals(castOther.getBaggageConcept()) ) )
 && ( (this.getSeatMaskCode()==castOther.getSeatMaskCode()) || ( this.getSeatMaskCode()!=null && castOther.getSeatMaskCode()!=null && this.getSeatMaskCode().equals(castOther.getSeatMaskCode()) ) )
 && ( (this.getUldCode()==castOther.getUldCode()) || ( this.getUldCode()!=null && castOther.getUldCode()!=null && this.getUldCode().equals(castOther.getUldCode()) ) )
 && ( (this.getFlightStatus()==castOther.getFlightStatus()) || ( this.getFlightStatus()!=null && castOther.getFlightStatus()!=null && this.getFlightStatus().equals(castOther.getFlightStatus()) ) )
 && ( (this.getProgress()==castOther.getProgress()) || ( this.getProgress()!=null && castOther.getProgress()!=null && this.getProgress().equals(castOther.getProgress()) ) )
 && ( (this.getDownloadDate()==castOther.getDownloadDate()) || ( this.getDownloadDate()!=null && castOther.getDownloadDate()!=null && this.getDownloadDate().equals(castOther.getDownloadDate()) ) )
 && ( (this.getTimeStamp()==castOther.getTimeStamp()) || ( this.getTimeStamp()!=null && castOther.getTimeStamp()!=null && this.getTimeStamp().equals(castOther.getTimeStamp()) ) )
 && ( (this.getFlightNumberExp()==castOther.getFlightNumberExp()) || ( this.getFlightNumberExp()!=null && castOther.getFlightNumberExp()!=null && this.getFlightNumberExp().equals(castOther.getFlightNumberExp()) ) )
 && ( (this.getCreated()==castOther.getCreated()) || ( this.getCreated()!=null && castOther.getCreated()!=null && this.getCreated().equals(castOther.getCreated()) ) )
 && ( (this.getUsrCreated()==castOther.getUsrCreated()) || ( this.getUsrCreated()!=null && castOther.getUsrCreated()!=null && this.getUsrCreated().equals(castOther.getUsrCreated()) ) )
 && ( (this.getChanged()==castOther.getChanged()) || ( this.getChanged()!=null && castOther.getChanged()!=null && this.getChanged().equals(castOther.getChanged()) ) )
 && ( (this.getUsrChanged()==castOther.getUsrChanged()) || ( this.getUsrChanged()!=null && castOther.getUsrChanged()!=null && this.getUsrChanged().equals(castOther.getUsrChanged()) ) )
 && ( (this.getFfNotified()==castOther.getFfNotified()) || ( this.getFfNotified()!=null && castOther.getFfNotified()!=null && this.getFfNotified().equals(castOther.getFfNotified()) ) )
 && ( (this.getPdCount()==castOther.getPdCount()) || ( this.getPdCount()!=null && castOther.getPdCount()!=null && this.getPdCount().equals(castOther.getPdCount()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getScheduledDate()==castOther.getScheduledDate()) || ( this.getScheduledDate()!=null && castOther.getScheduledDate()!=null && this.getScheduledDate().equals(castOther.getScheduledDate()) ) )
 && ( (this.getArrDepFlag()==castOther.getArrDepFlag()) || ( this.getArrDepFlag()!=null && castOther.getArrDepFlag()!=null && this.getArrDepFlag().equals(castOther.getArrDepFlag()) ) )
 && ( (this.getCreatedDate()==castOther.getCreatedDate()) || ( this.getCreatedDate()!=null && castOther.getCreatedDate()!=null && this.getCreatedDate().equals(castOther.getCreatedDate()) ) )
 && ( (this.getDmlFlag()==castOther.getDmlFlag()) || ( this.getDmlFlag()!=null && castOther.getDmlFlag()!=null && this.getDmlFlag().equals(castOther.getDmlFlag()) ) )
 && ( (this.getAdbSubject()==castOther.getAdbSubject()) || ( this.getAdbSubject()!=null && castOther.getAdbSubject()!=null && this.getAdbSubject().equals(castOther.getAdbSubject()) ) )
 && ( (this.getAdbSequence()==castOther.getAdbSequence()) || ( this.getAdbSequence()!=null && castOther.getAdbSequence()!=null && this.getAdbSequence().equals(castOther.getAdbSequence()) ) )
 && ( (this.getAdbSetSequence()==castOther.getAdbSetSequence()) || ( this.getAdbSetSequence()!=null && castOther.getAdbSetSequence()!=null && this.getAdbSetSequence().equals(castOther.getAdbSetSequence()) ) )
 && ( (this.getAdbTimestamp()==castOther.getAdbTimestamp()) || ( this.getAdbTimestamp()!=null && castOther.getAdbTimestamp()!=null && this.getAdbTimestamp().equals(castOther.getAdbTimestamp()) ) )
 && ( (this.getAdbOpcode()==castOther.getAdbOpcode()) || ( this.getAdbOpcode()!=null && castOther.getAdbOpcode()!=null && this.getAdbOpcode().equals(castOther.getAdbOpcode()) ) )
 && ( (this.getAdbUpdateAll()==castOther.getAdbUpdateAll()) || ( this.getAdbUpdateAll()!=null && castOther.getAdbUpdateAll()!=null && this.getAdbUpdateAll().equals(castOther.getAdbUpdateAll()) ) )
 && ( (this.getAdbRefObject()==castOther.getAdbRefObject()) || ( this.getAdbRefObject()!=null && castOther.getAdbRefObject()!=null && this.getAdbRefObject().equals(castOther.getAdbRefObject()) ) )
 && ( (this.getAdbLDeliveryStatus()==castOther.getAdbLDeliveryStatus()) || ( this.getAdbLDeliveryStatus()!=null && castOther.getAdbLDeliveryStatus()!=null && this.getAdbLDeliveryStatus().equals(castOther.getAdbLDeliveryStatus()) ) )
 && ( (this.getAdbLCmsequence()==castOther.getAdbLCmsequence()) || ( this.getAdbLCmsequence()!=null && castOther.getAdbLCmsequence()!=null && this.getAdbLCmsequence().equals(castOther.getAdbLCmsequence()) ) )
 && ( (this.getAdbTrackingid()==castOther.getAdbTrackingid()) || ( this.getAdbTrackingid()!=null && castOther.getAdbTrackingid()!=null && this.getAdbTrackingid().equals(castOther.getAdbTrackingid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFltSnapshotDay() == null ? 0 : this.getFltSnapshotDay().hashCode() );
         result = 37 * result + ( getFltSeq() == null ? 0 : this.getFltSeq().hashCode() );
         result = 37 * result + ( getMflId() == null ? 0 : this.getMflId().hashCode() );
         result = 37 * result + ( getAirlineDesignator() == null ? 0 : this.getAirlineDesignator().hashCode() );
         result = 37 * result + ( getAirlineDesignatorExp() == null ? 0 : this.getAirlineDesignatorExp().hashCode() );
         result = 37 * result + ( getFlightNumber() == null ? 0 : this.getFlightNumber().hashCode() );
         result = 37 * result + ( getOperationDate() == null ? 0 : this.getOperationDate().hashCode() );
         result = 37 * result + ( getOperationTime() == null ? 0 : this.getOperationTime().hashCode() );
         result = 37 * result + ( getOperationDateGmt() == null ? 0 : this.getOperationDateGmt().hashCode() );
         result = 37 * result + ( getOperationTimeGmt() == null ? 0 : this.getOperationTimeGmt().hashCode() );
         result = 37 * result + ( getLatestDepartureDate() == null ? 0 : this.getLatestDepartureDate().hashCode() );
         result = 37 * result + ( getLatestDepartureTime() == null ? 0 : this.getLatestDepartureTime().hashCode() );
         result = 37 * result + ( getLatestDepartureDateGmt() == null ? 0 : this.getLatestDepartureDateGmt().hashCode() );
         result = 37 * result + ( getLatestDepartureTimeGmt() == null ? 0 : this.getLatestDepartureTimeGmt().hashCode() );
         result = 37 * result + ( getBoardPoint() == null ? 0 : this.getBoardPoint().hashCode() );
         result = 37 * result + ( getAircraftType() == null ? 0 : this.getAircraftType().hashCode() );
         result = 37 * result + ( getClassConfiguration() == null ? 0 : this.getClassConfiguration().hashCode() );
         result = 37 * result + ( getRegistrationNumber() == null ? 0 : this.getRegistrationNumber().hashCode() );
         result = 37 * result + ( getPantryCode() == null ? 0 : this.getPantryCode().hashCode() );
         result = 37 * result + ( getCrewCode() == null ? 0 : this.getCrewCode().hashCode() );
         result = 37 * result + ( getGateNumber() == null ? 0 : this.getGateNumber().hashCode() );
         result = 37 * result + ( getBaggageConcept() == null ? 0 : this.getBaggageConcept().hashCode() );
         result = 37 * result + ( getSeatMaskCode() == null ? 0 : this.getSeatMaskCode().hashCode() );
         result = 37 * result + ( getUldCode() == null ? 0 : this.getUldCode().hashCode() );
         result = 37 * result + ( getFlightStatus() == null ? 0 : this.getFlightStatus().hashCode() );
         result = 37 * result + ( getProgress() == null ? 0 : this.getProgress().hashCode() );
         result = 37 * result + ( getDownloadDate() == null ? 0 : this.getDownloadDate().hashCode() );
         result = 37 * result + ( getTimeStamp() == null ? 0 : this.getTimeStamp().hashCode() );
         result = 37 * result + ( getFlightNumberExp() == null ? 0 : this.getFlightNumberExp().hashCode() );
         result = 37 * result + ( getCreated() == null ? 0 : this.getCreated().hashCode() );
         result = 37 * result + ( getUsrCreated() == null ? 0 : this.getUsrCreated().hashCode() );
         result = 37 * result + ( getChanged() == null ? 0 : this.getChanged().hashCode() );
         result = 37 * result + ( getUsrChanged() == null ? 0 : this.getUsrChanged().hashCode() );
         result = 37 * result + ( getFfNotified() == null ? 0 : this.getFfNotified().hashCode() );
         result = 37 * result + ( getPdCount() == null ? 0 : this.getPdCount().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getScheduledDate() == null ? 0 : this.getScheduledDate().hashCode() );
         result = 37 * result + ( getArrDepFlag() == null ? 0 : this.getArrDepFlag().hashCode() );
         result = 37 * result + ( getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode() );
         result = 37 * result + ( getDmlFlag() == null ? 0 : this.getDmlFlag().hashCode() );
         result = 37 * result + ( getAdbSubject() == null ? 0 : this.getAdbSubject().hashCode() );
         result = 37 * result + ( getAdbSequence() == null ? 0 : this.getAdbSequence().hashCode() );
         result = 37 * result + ( getAdbSetSequence() == null ? 0 : this.getAdbSetSequence().hashCode() );
         result = 37 * result + ( getAdbTimestamp() == null ? 0 : this.getAdbTimestamp().hashCode() );
         result = 37 * result + ( getAdbOpcode() == null ? 0 : this.getAdbOpcode().hashCode() );
         result = 37 * result + ( getAdbUpdateAll() == null ? 0 : this.getAdbUpdateAll().hashCode() );
         result = 37 * result + ( getAdbRefObject() == null ? 0 : this.getAdbRefObject().hashCode() );
         result = 37 * result + ( getAdbLDeliveryStatus() == null ? 0 : this.getAdbLDeliveryStatus().hashCode() );
         result = 37 * result + ( getAdbLCmsequence() == null ? 0 : this.getAdbLCmsequence().hashCode() );
         result = 37 * result + ( getAdbTrackingid() == null ? 0 : this.getAdbTrackingid().hashCode() );
         return result;
   }   


}


