package com.solace.connector.db.pull.entity;
// Generated 19-Sep-2023, 11:35:03 am by Hibernate Tools 5.6.2.Final


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sector generated by hbm2java
 */
@Entity
@Table(name="SECTOR"
    
)
public class Sector  implements java.io.Serializable {


     private BigDecimal sectorId;
     private BigDecimal empId;
     private String sectorName;
     private Set<Department> departments = new HashSet<Department>(0);

    public Sector() {
    }

	
    public Sector(BigDecimal sectorId, String sectorName) {
        this.sectorId = sectorId;
        this.sectorName = sectorName;
    }
    public Sector(BigDecimal sectorId, BigDecimal empId, String sectorName, Set<Department> departments) {
       this.sectorId = sectorId;
       this.empId = empId;
       this.sectorName = sectorName;
       this.departments = departments;
    }
   
     @Id 

    
    @Column(name="SECTOR_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getSectorId() {
        return this.sectorId;
    }
    
    public void setSectorId(BigDecimal sectorId) {
        this.sectorId = sectorId;
    }

    
    @Column(name="EMP_ID", precision=22, scale=0)
    public BigDecimal getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(BigDecimal empId) {
        this.empId = empId;
    }

    
    @Column(name="SECTOR_NAME", nullable=false, length=200)
    public String getSectorName() {
        return this.sectorName;
    }
    
    public void setSectorName(String sectorName) {
        this.sectorName = sectorName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sector")
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }




}


