package com.solace.connector.db.pull.entity;
// Generated 19-Sep-2023, 11:35:03 am by Hibernate Tools 5.6.2.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblCamMaxxess generated by hbm2java
 */
@Entity
@Table(name="TBL_CAM_MAXXESS"
    
)
public class TblCamMaxxess  implements java.io.Serializable {


     private TblCamMaxxessId id;

    public TblCamMaxxess() {
    }

    public TblCamMaxxess(TblCamMaxxessId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="costcenterCode", column=@Column(name="COSTCENTER_CODE", nullable=false, length=10) ), 
        @AttributeOverride(name="gradeCode", column=@Column(name="GRADE_CODE", nullable=false, length=10) ), 
        @AttributeOverride(name="employeeName", column=@Column(name="EMPLOYEE_NAME", length=100) ), 
        @AttributeOverride(name="updateComment", column=@Column(name="UPDATE_COMMENT", length=1000) ), 
        @AttributeOverride(name="lastUpdated", column=@Column(name="LAST_UPDATED", nullable=false, length=7) ), 
        @AttributeOverride(name="isActive", column=@Column(name="IS_ACTIVE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="employeeType", column=@Column(name="EMPLOYEE_TYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="contactDetail", column=@Column(name="CONTACT_DETAIL", length=100) ), 
        @AttributeOverride(name="firstName", column=@Column(name="FIRST_NAME", length=200) ), 
        @AttributeOverride(name="middleName", column=@Column(name="MIDDLE_NAME", length=200) ), 
        @AttributeOverride(name="lastName", column=@Column(name="LAST_NAME", length=200) ), 
        @AttributeOverride(name="insertedDate", column=@Column(name="INSERTED_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="maxxessId", column=@Column(name="MAXXESS_ID", precision=10, scale=0) ), 
        @AttributeOverride(name="employeeLastUpdated", column=@Column(name="EMPLOYEE_LAST_UPDATED", length=7) ), 
        @AttributeOverride(name="ccgrjbLastUpdated", column=@Column(name="CCGRJB_LAST_UPDATED", length=7) ), 
        @AttributeOverride(name="jobCode", column=@Column(name="JOB_CODE", nullable=false, length=10) ), 
        @AttributeOverride(name="lineMgrId", column=@Column(name="LINE_MGR_ID", length=10) ), 
        @AttributeOverride(name="cardNumber", column=@Column(name="CARD_NUMBER", nullable=false, length=20) ), 
        @AttributeOverride(name="issueDate", column=@Column(name="ISSUE_DATE", nullable=false, length=20) ), 
        @AttributeOverride(name="expiryDate", column=@Column(name="EXPIRY_DATE", nullable=false, length=20) ), 
        @AttributeOverride(name="blockedDate", column=@Column(name="BLOCKED_DATE", length=7) ), 
        @AttributeOverride(name="processedType", column=@Column(name="PROCESSED_TYPE", precision=1, scale=0) ), 
        @AttributeOverride(name="processedDate", column=@Column(name="PROCESSED_DATE", length=7) ), 
        @AttributeOverride(name="cardTypeId", column=@Column(name="CARD_TYPE_ID", precision=1, scale=0) ), 
        @AttributeOverride(name="empcardIsMaxxessUpdated", column=@Column(name="EMPCARD_IS_MAXXESS_UPDATED", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="empaccessIsMaxxessUpdated", column=@Column(name="EMPACCESS_IS_MAXXESS_UPDATED", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="costcenterIsActive", column=@Column(name="COSTCENTER_IS_ACTIVE", precision=1, scale=0) ), 
        @AttributeOverride(name="empIsMaxxessUpdated", column=@Column(name="EMP_IS_MAXXESS_UPDATED", precision=1, scale=0) ), 
        @AttributeOverride(name="cardIsActive", column=@Column(name="CARD_IS_ACTIVE", precision=1, scale=0) ), 
        @AttributeOverride(name="adbSubject", column=@Column(name="ADB_SUBJECT") ), 
        @AttributeOverride(name="adbSequence", column=@Column(name="ADB_SEQUENCE", precision=22, scale=0) ), 
        @AttributeOverride(name="adbSetSequence", column=@Column(name="ADB_SET_SEQUENCE", precision=22, scale=0) ), 
        @AttributeOverride(name="adbTimestamp", column=@Column(name="ADB_TIMESTAMP", nullable=false, length=7) ), 
        @AttributeOverride(name="adbOpcode", column=@Column(name="ADB_OPCODE", precision=22, scale=0) ), 
        @AttributeOverride(name="adbUpdateAll", column=@Column(name="ADB_UPDATE_ALL", precision=22, scale=0) ), 
        @AttributeOverride(name="adbRefObject", column=@Column(name="ADB_REF_OBJECT", length=64) ), 
        @AttributeOverride(name="adbLDeliveryStatus", column=@Column(name="ADB_L_DELIVERY_STATUS", length=1) ), 
        @AttributeOverride(name="adbLCmsequence", column=@Column(name="ADB_L_CMSEQUENCE", precision=38, scale=0) ), 
        @AttributeOverride(name="adbTrackingid", column=@Column(name="ADB_TRACKINGID", length=40) ), 
        @AttributeOverride(name="anprVehicleplate1", column=@Column(name="ANPR_VEHICLEPLATE1", length=50) ), 
        @AttributeOverride(name="anprVehiclemodel1", column=@Column(name="ANPR_VEHICLEMODEL1", length=150) ), 
        @AttributeOverride(name="anprVehiclecolor1", column=@Column(name="ANPR_VEHICLECOLOR1", length=100) ), 
        @AttributeOverride(name="anprVehicleplate2", column=@Column(name="ANPR_VEHICLEPLATE2", length=50) ), 
        @AttributeOverride(name="anprVehiclemodel2", column=@Column(name="ANPR_VEHICLEMODEL2", length=150) ), 
        @AttributeOverride(name="anprVehiclecolor2", column=@Column(name="ANPR_VEHICLECOLOR2", length=100) ), 
        @AttributeOverride(name="anprVehicleplate3", column=@Column(name="ANPR_VEHICLEPLATE3", length=50) ), 
        @AttributeOverride(name="anprVehiclemodel3", column=@Column(name="ANPR_VEHICLEMODEL3", length=150) ), 
        @AttributeOverride(name="anprVehiclecolor3", column=@Column(name="ANPR_VEHICLECOLOR3", length=100) ), 
        @AttributeOverride(name="empCarparkIsMaxxessUpdated", column=@Column(name="EMP_CARPARK_IS_MAXXESS_UPDATED", precision=1, scale=0) ) } )
    public TblCamMaxxessId getId() {
        return this.id;
    }
    
    public void setId(TblCamMaxxessId id) {
        this.id = id;
    }




}


