package com.solace.connector.db.pull.entity;
// Generated 19-Sep-2023, 11:35:03 am by Hibernate Tools 5.6.2.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblCamMaxxessId generated by hbm2java
 */
@Embeddable
public class TblCamMaxxessId  implements java.io.Serializable {


     private String employeeId;
     private String costcenterCode;
     private String gradeCode;
     private String employeeName;
     private String updateComment;
     private Date lastUpdated;
     private BigDecimal isActive;
     private BigDecimal employeeType;
     private String contactDetail;
     private String firstName;
     private String middleName;
     private String lastName;
     private Date insertedDate;
     private BigDecimal maxxessId;
     private Date employeeLastUpdated;
     private Date ccgrjbLastUpdated;
     private String jobCode;
     private String lineMgrId;
     private String cardNumber;
     private String issueDate;
     private String expiryDate;
     private Date blockedDate;
     private BigDecimal processedType;
     private Date processedDate;
     private BigDecimal cardTypeId;
     private BigDecimal empcardIsMaxxessUpdated;
     private BigDecimal empaccessIsMaxxessUpdated;
     private BigDecimal costcenterIsActive;
     private BigDecimal empIsMaxxessUpdated;
     private BigDecimal cardIsActive;
     private String adbSubject;
     private BigDecimal adbSequence;
     private BigDecimal adbSetSequence;
     private Date adbTimestamp;
     private BigDecimal adbOpcode;
     private BigDecimal adbUpdateAll;
     private String adbRefObject;
     private Character adbLDeliveryStatus;
     private BigDecimal adbLCmsequence;
     private String adbTrackingid;
     private String anprVehicleplate1;
     private String anprVehiclemodel1;
     private String anprVehiclecolor1;
     private String anprVehicleplate2;
     private String anprVehiclemodel2;
     private String anprVehiclecolor2;
     private String anprVehicleplate3;
     private String anprVehiclemodel3;
     private String anprVehiclecolor3;
     private BigDecimal empCarparkIsMaxxessUpdated;

    public TblCamMaxxessId() {
    }

	
    public TblCamMaxxessId(String employeeId, String costcenterCode, String gradeCode, Date lastUpdated, BigDecimal isActive, BigDecimal employeeType, Date insertedDate, String jobCode, String cardNumber, String issueDate, String expiryDate, BigDecimal empcardIsMaxxessUpdated, BigDecimal empaccessIsMaxxessUpdated, Date adbTimestamp) {
        this.employeeId = employeeId;
        this.costcenterCode = costcenterCode;
        this.gradeCode = gradeCode;
        this.lastUpdated = lastUpdated;
        this.isActive = isActive;
        this.employeeType = employeeType;
        this.insertedDate = insertedDate;
        this.jobCode = jobCode;
        this.cardNumber = cardNumber;
        this.issueDate = issueDate;
        this.expiryDate = expiryDate;
        this.empcardIsMaxxessUpdated = empcardIsMaxxessUpdated;
        this.empaccessIsMaxxessUpdated = empaccessIsMaxxessUpdated;
        this.adbTimestamp = adbTimestamp;
    }
    public TblCamMaxxessId(String employeeId, String costcenterCode, String gradeCode, String employeeName, String updateComment, Date lastUpdated, BigDecimal isActive, BigDecimal employeeType, String contactDetail, String firstName, String middleName, String lastName, Date insertedDate, BigDecimal maxxessId, Date employeeLastUpdated, Date ccgrjbLastUpdated, String jobCode, String lineMgrId, String cardNumber, String issueDate, String expiryDate, Date blockedDate, BigDecimal processedType, Date processedDate, BigDecimal cardTypeId, BigDecimal empcardIsMaxxessUpdated, BigDecimal empaccessIsMaxxessUpdated, BigDecimal costcenterIsActive, BigDecimal empIsMaxxessUpdated, BigDecimal cardIsActive, String adbSubject, BigDecimal adbSequence, BigDecimal adbSetSequence, Date adbTimestamp, BigDecimal adbOpcode, BigDecimal adbUpdateAll, String adbRefObject, Character adbLDeliveryStatus, BigDecimal adbLCmsequence, String adbTrackingid, String anprVehicleplate1, String anprVehiclemodel1, String anprVehiclecolor1, String anprVehicleplate2, String anprVehiclemodel2, String anprVehiclecolor2, String anprVehicleplate3, String anprVehiclemodel3, String anprVehiclecolor3, BigDecimal empCarparkIsMaxxessUpdated) {
       this.employeeId = employeeId;
       this.costcenterCode = costcenterCode;
       this.gradeCode = gradeCode;
       this.employeeName = employeeName;
       this.updateComment = updateComment;
       this.lastUpdated = lastUpdated;
       this.isActive = isActive;
       this.employeeType = employeeType;
       this.contactDetail = contactDetail;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.insertedDate = insertedDate;
       this.maxxessId = maxxessId;
       this.employeeLastUpdated = employeeLastUpdated;
       this.ccgrjbLastUpdated = ccgrjbLastUpdated;
       this.jobCode = jobCode;
       this.lineMgrId = lineMgrId;
       this.cardNumber = cardNumber;
       this.issueDate = issueDate;
       this.expiryDate = expiryDate;
       this.blockedDate = blockedDate;
       this.processedType = processedType;
       this.processedDate = processedDate;
       this.cardTypeId = cardTypeId;
       this.empcardIsMaxxessUpdated = empcardIsMaxxessUpdated;
       this.empaccessIsMaxxessUpdated = empaccessIsMaxxessUpdated;
       this.costcenterIsActive = costcenterIsActive;
       this.empIsMaxxessUpdated = empIsMaxxessUpdated;
       this.cardIsActive = cardIsActive;
       this.adbSubject = adbSubject;
       this.adbSequence = adbSequence;
       this.adbSetSequence = adbSetSequence;
       this.adbTimestamp = adbTimestamp;
       this.adbOpcode = adbOpcode;
       this.adbUpdateAll = adbUpdateAll;
       this.adbRefObject = adbRefObject;
       this.adbLDeliveryStatus = adbLDeliveryStatus;
       this.adbLCmsequence = adbLCmsequence;
       this.adbTrackingid = adbTrackingid;
       this.anprVehicleplate1 = anprVehicleplate1;
       this.anprVehiclemodel1 = anprVehiclemodel1;
       this.anprVehiclecolor1 = anprVehiclecolor1;
       this.anprVehicleplate2 = anprVehicleplate2;
       this.anprVehiclemodel2 = anprVehiclemodel2;
       this.anprVehiclecolor2 = anprVehiclecolor2;
       this.anprVehicleplate3 = anprVehicleplate3;
       this.anprVehiclemodel3 = anprVehiclemodel3;
       this.anprVehiclecolor3 = anprVehiclecolor3;
       this.empCarparkIsMaxxessUpdated = empCarparkIsMaxxessUpdated;
    }
   


    @Column(name="EMPLOYEE_ID", nullable=false, length=10)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }


    @Column(name="COSTCENTER_CODE", nullable=false, length=10)
    public String getCostcenterCode() {
        return this.costcenterCode;
    }
    
    public void setCostcenterCode(String costcenterCode) {
        this.costcenterCode = costcenterCode;
    }


    @Column(name="GRADE_CODE", nullable=false, length=10)
    public String getGradeCode() {
        return this.gradeCode;
    }
    
    public void setGradeCode(String gradeCode) {
        this.gradeCode = gradeCode;
    }


    @Column(name="EMPLOYEE_NAME", length=100)
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }


    @Column(name="UPDATE_COMMENT", length=1000)
    public String getUpdateComment() {
        return this.updateComment;
    }
    
    public void setUpdateComment(String updateComment) {
        this.updateComment = updateComment;
    }


    @Column(name="LAST_UPDATED", nullable=false, length=7)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }


    @Column(name="IS_ACTIVE", nullable=false, precision=1, scale=0)
    public BigDecimal getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(BigDecimal isActive) {
        this.isActive = isActive;
    }


    @Column(name="EMPLOYEE_TYPE", nullable=false, precision=1, scale=0)
    public BigDecimal getEmployeeType() {
        return this.employeeType;
    }
    
    public void setEmployeeType(BigDecimal employeeType) {
        this.employeeType = employeeType;
    }


    @Column(name="CONTACT_DETAIL", length=100)
    public String getContactDetail() {
        return this.contactDetail;
    }
    
    public void setContactDetail(String contactDetail) {
        this.contactDetail = contactDetail;
    }


    @Column(name="FIRST_NAME", length=200)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    @Column(name="MIDDLE_NAME", length=200)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }


    @Column(name="LAST_NAME", length=200)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    @Column(name="INSERTED_DATE", nullable=false, length=7)
    public Date getInsertedDate() {
        return this.insertedDate;
    }
    
    public void setInsertedDate(Date insertedDate) {
        this.insertedDate = insertedDate;
    }


    @Column(name="MAXXESS_ID", precision=10, scale=0)
    public BigDecimal getMaxxessId() {
        return this.maxxessId;
    }
    
    public void setMaxxessId(BigDecimal maxxessId) {
        this.maxxessId = maxxessId;
    }


    @Column(name="EMPLOYEE_LAST_UPDATED", length=7)
    public Date getEmployeeLastUpdated() {
        return this.employeeLastUpdated;
    }
    
    public void setEmployeeLastUpdated(Date employeeLastUpdated) {
        this.employeeLastUpdated = employeeLastUpdated;
    }


    @Column(name="CCGRJB_LAST_UPDATED", length=7)
    public Date getCcgrjbLastUpdated() {
        return this.ccgrjbLastUpdated;
    }
    
    public void setCcgrjbLastUpdated(Date ccgrjbLastUpdated) {
        this.ccgrjbLastUpdated = ccgrjbLastUpdated;
    }


    @Column(name="JOB_CODE", nullable=false, length=10)
    public String getJobCode() {
        return this.jobCode;
    }
    
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }


    @Column(name="LINE_MGR_ID", length=10)
    public String getLineMgrId() {
        return this.lineMgrId;
    }
    
    public void setLineMgrId(String lineMgrId) {
        this.lineMgrId = lineMgrId;
    }


    @Column(name="CARD_NUMBER", nullable=false, length=20)
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }


    @Column(name="ISSUE_DATE", nullable=false, length=20)
    public String getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(String issueDate) {
        this.issueDate = issueDate;
    }


    @Column(name="EXPIRY_DATE", nullable=false, length=20)
    public String getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(String expiryDate) {
        this.expiryDate = expiryDate;
    }


    @Column(name="BLOCKED_DATE", length=7)
    public Date getBlockedDate() {
        return this.blockedDate;
    }
    
    public void setBlockedDate(Date blockedDate) {
        this.blockedDate = blockedDate;
    }


    @Column(name="PROCESSED_TYPE", precision=1, scale=0)
    public BigDecimal getProcessedType() {
        return this.processedType;
    }
    
    public void setProcessedType(BigDecimal processedType) {
        this.processedType = processedType;
    }


    @Column(name="PROCESSED_DATE", length=7)
    public Date getProcessedDate() {
        return this.processedDate;
    }
    
    public void setProcessedDate(Date processedDate) {
        this.processedDate = processedDate;
    }


    @Column(name="CARD_TYPE_ID", precision=1, scale=0)
    public BigDecimal getCardTypeId() {
        return this.cardTypeId;
    }
    
    public void setCardTypeId(BigDecimal cardTypeId) {
        this.cardTypeId = cardTypeId;
    }


    @Column(name="EMPCARD_IS_MAXXESS_UPDATED", nullable=false, precision=1, scale=0)
    public BigDecimal getEmpcardIsMaxxessUpdated() {
        return this.empcardIsMaxxessUpdated;
    }
    
    public void setEmpcardIsMaxxessUpdated(BigDecimal empcardIsMaxxessUpdated) {
        this.empcardIsMaxxessUpdated = empcardIsMaxxessUpdated;
    }


    @Column(name="EMPACCESS_IS_MAXXESS_UPDATED", nullable=false, precision=1, scale=0)
    public BigDecimal getEmpaccessIsMaxxessUpdated() {
        return this.empaccessIsMaxxessUpdated;
    }
    
    public void setEmpaccessIsMaxxessUpdated(BigDecimal empaccessIsMaxxessUpdated) {
        this.empaccessIsMaxxessUpdated = empaccessIsMaxxessUpdated;
    }


    @Column(name="COSTCENTER_IS_ACTIVE", precision=1, scale=0)
    public BigDecimal getCostcenterIsActive() {
        return this.costcenterIsActive;
    }
    
    public void setCostcenterIsActive(BigDecimal costcenterIsActive) {
        this.costcenterIsActive = costcenterIsActive;
    }


    @Column(name="EMP_IS_MAXXESS_UPDATED", precision=1, scale=0)
    public BigDecimal getEmpIsMaxxessUpdated() {
        return this.empIsMaxxessUpdated;
    }
    
    public void setEmpIsMaxxessUpdated(BigDecimal empIsMaxxessUpdated) {
        this.empIsMaxxessUpdated = empIsMaxxessUpdated;
    }


    @Column(name="CARD_IS_ACTIVE", precision=1, scale=0)
    public BigDecimal getCardIsActive() {
        return this.cardIsActive;
    }
    
    public void setCardIsActive(BigDecimal cardIsActive) {
        this.cardIsActive = cardIsActive;
    }


    @Column(name="ADB_SUBJECT")
    public String getAdbSubject() {
        return this.adbSubject;
    }
    
    public void setAdbSubject(String adbSubject) {
        this.adbSubject = adbSubject;
    }


    @Column(name="ADB_SEQUENCE", precision=22, scale=0)
    public BigDecimal getAdbSequence() {
        return this.adbSequence;
    }
    
    public void setAdbSequence(BigDecimal adbSequence) {
        this.adbSequence = adbSequence;
    }


    @Column(name="ADB_SET_SEQUENCE", precision=22, scale=0)
    public BigDecimal getAdbSetSequence() {
        return this.adbSetSequence;
    }
    
    public void setAdbSetSequence(BigDecimal adbSetSequence) {
        this.adbSetSequence = adbSetSequence;
    }


    @Column(name="ADB_TIMESTAMP", nullable=false, length=7)
    public Date getAdbTimestamp() {
        return this.adbTimestamp;
    }
    
    public void setAdbTimestamp(Date adbTimestamp) {
        this.adbTimestamp = adbTimestamp;
    }


    @Column(name="ADB_OPCODE", precision=22, scale=0)
    public BigDecimal getAdbOpcode() {
        return this.adbOpcode;
    }
    
    public void setAdbOpcode(BigDecimal adbOpcode) {
        this.adbOpcode = adbOpcode;
    }


    @Column(name="ADB_UPDATE_ALL", precision=22, scale=0)
    public BigDecimal getAdbUpdateAll() {
        return this.adbUpdateAll;
    }
    
    public void setAdbUpdateAll(BigDecimal adbUpdateAll) {
        this.adbUpdateAll = adbUpdateAll;
    }


    @Column(name="ADB_REF_OBJECT", length=64)
    public String getAdbRefObject() {
        return this.adbRefObject;
    }
    
    public void setAdbRefObject(String adbRefObject) {
        this.adbRefObject = adbRefObject;
    }


    @Column(name="ADB_L_DELIVERY_STATUS", length=1)
    public Character getAdbLDeliveryStatus() {
        return this.adbLDeliveryStatus;
    }
    
    public void setAdbLDeliveryStatus(Character adbLDeliveryStatus) {
        this.adbLDeliveryStatus = adbLDeliveryStatus;
    }


    @Column(name="ADB_L_CMSEQUENCE", precision=38, scale=0)
    public BigDecimal getAdbLCmsequence() {
        return this.adbLCmsequence;
    }
    
    public void setAdbLCmsequence(BigDecimal adbLCmsequence) {
        this.adbLCmsequence = adbLCmsequence;
    }


    @Column(name="ADB_TRACKINGID", length=40)
    public String getAdbTrackingid() {
        return this.adbTrackingid;
    }
    
    public void setAdbTrackingid(String adbTrackingid) {
        this.adbTrackingid = adbTrackingid;
    }


    @Column(name="ANPR_VEHICLEPLATE1", length=50)
    public String getAnprVehicleplate1() {
        return this.anprVehicleplate1;
    }
    
    public void setAnprVehicleplate1(String anprVehicleplate1) {
        this.anprVehicleplate1 = anprVehicleplate1;
    }


    @Column(name="ANPR_VEHICLEMODEL1", length=150)
    public String getAnprVehiclemodel1() {
        return this.anprVehiclemodel1;
    }
    
    public void setAnprVehiclemodel1(String anprVehiclemodel1) {
        this.anprVehiclemodel1 = anprVehiclemodel1;
    }


    @Column(name="ANPR_VEHICLECOLOR1", length=100)
    public String getAnprVehiclecolor1() {
        return this.anprVehiclecolor1;
    }
    
    public void setAnprVehiclecolor1(String anprVehiclecolor1) {
        this.anprVehiclecolor1 = anprVehiclecolor1;
    }


    @Column(name="ANPR_VEHICLEPLATE2", length=50)
    public String getAnprVehicleplate2() {
        return this.anprVehicleplate2;
    }
    
    public void setAnprVehicleplate2(String anprVehicleplate2) {
        this.anprVehicleplate2 = anprVehicleplate2;
    }


    @Column(name="ANPR_VEHICLEMODEL2", length=150)
    public String getAnprVehiclemodel2() {
        return this.anprVehiclemodel2;
    }
    
    public void setAnprVehiclemodel2(String anprVehiclemodel2) {
        this.anprVehiclemodel2 = anprVehiclemodel2;
    }


    @Column(name="ANPR_VEHICLECOLOR2", length=100)
    public String getAnprVehiclecolor2() {
        return this.anprVehiclecolor2;
    }
    
    public void setAnprVehiclecolor2(String anprVehiclecolor2) {
        this.anprVehiclecolor2 = anprVehiclecolor2;
    }


    @Column(name="ANPR_VEHICLEPLATE3", length=50)
    public String getAnprVehicleplate3() {
        return this.anprVehicleplate3;
    }
    
    public void setAnprVehicleplate3(String anprVehicleplate3) {
        this.anprVehicleplate3 = anprVehicleplate3;
    }


    @Column(name="ANPR_VEHICLEMODEL3", length=150)
    public String getAnprVehiclemodel3() {
        return this.anprVehiclemodel3;
    }
    
    public void setAnprVehiclemodel3(String anprVehiclemodel3) {
        this.anprVehiclemodel3 = anprVehiclemodel3;
    }


    @Column(name="ANPR_VEHICLECOLOR3", length=100)
    public String getAnprVehiclecolor3() {
        return this.anprVehiclecolor3;
    }
    
    public void setAnprVehiclecolor3(String anprVehiclecolor3) {
        this.anprVehiclecolor3 = anprVehiclecolor3;
    }


    @Column(name="EMP_CARPARK_IS_MAXXESS_UPDATED", precision=1, scale=0)
    public BigDecimal getEmpCarparkIsMaxxessUpdated() {
        return this.empCarparkIsMaxxessUpdated;
    }
    
    public void setEmpCarparkIsMaxxessUpdated(BigDecimal empCarparkIsMaxxessUpdated) {
        this.empCarparkIsMaxxessUpdated = empCarparkIsMaxxessUpdated;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblCamMaxxessId) ) return false;
		 TblCamMaxxessId castOther = ( TblCamMaxxessId ) other; 
         
		 return ( (this.getEmployeeId()==castOther.getEmployeeId()) || ( this.getEmployeeId()!=null && castOther.getEmployeeId()!=null && this.getEmployeeId().equals(castOther.getEmployeeId()) ) )
 && ( (this.getCostcenterCode()==castOther.getCostcenterCode()) || ( this.getCostcenterCode()!=null && castOther.getCostcenterCode()!=null && this.getCostcenterCode().equals(castOther.getCostcenterCode()) ) )
 && ( (this.getGradeCode()==castOther.getGradeCode()) || ( this.getGradeCode()!=null && castOther.getGradeCode()!=null && this.getGradeCode().equals(castOther.getGradeCode()) ) )
 && ( (this.getEmployeeName()==castOther.getEmployeeName()) || ( this.getEmployeeName()!=null && castOther.getEmployeeName()!=null && this.getEmployeeName().equals(castOther.getEmployeeName()) ) )
 && ( (this.getUpdateComment()==castOther.getUpdateComment()) || ( this.getUpdateComment()!=null && castOther.getUpdateComment()!=null && this.getUpdateComment().equals(castOther.getUpdateComment()) ) )
 && ( (this.getLastUpdated()==castOther.getLastUpdated()) || ( this.getLastUpdated()!=null && castOther.getLastUpdated()!=null && this.getLastUpdated().equals(castOther.getLastUpdated()) ) )
 && ( (this.getIsActive()==castOther.getIsActive()) || ( this.getIsActive()!=null && castOther.getIsActive()!=null && this.getIsActive().equals(castOther.getIsActive()) ) )
 && ( (this.getEmployeeType()==castOther.getEmployeeType()) || ( this.getEmployeeType()!=null && castOther.getEmployeeType()!=null && this.getEmployeeType().equals(castOther.getEmployeeType()) ) )
 && ( (this.getContactDetail()==castOther.getContactDetail()) || ( this.getContactDetail()!=null && castOther.getContactDetail()!=null && this.getContactDetail().equals(castOther.getContactDetail()) ) )
 && ( (this.getFirstName()==castOther.getFirstName()) || ( this.getFirstName()!=null && castOther.getFirstName()!=null && this.getFirstName().equals(castOther.getFirstName()) ) )
 && ( (this.getMiddleName()==castOther.getMiddleName()) || ( this.getMiddleName()!=null && castOther.getMiddleName()!=null && this.getMiddleName().equals(castOther.getMiddleName()) ) )
 && ( (this.getLastName()==castOther.getLastName()) || ( this.getLastName()!=null && castOther.getLastName()!=null && this.getLastName().equals(castOther.getLastName()) ) )
 && ( (this.getInsertedDate()==castOther.getInsertedDate()) || ( this.getInsertedDate()!=null && castOther.getInsertedDate()!=null && this.getInsertedDate().equals(castOther.getInsertedDate()) ) )
 && ( (this.getMaxxessId()==castOther.getMaxxessId()) || ( this.getMaxxessId()!=null && castOther.getMaxxessId()!=null && this.getMaxxessId().equals(castOther.getMaxxessId()) ) )
 && ( (this.getEmployeeLastUpdated()==castOther.getEmployeeLastUpdated()) || ( this.getEmployeeLastUpdated()!=null && castOther.getEmployeeLastUpdated()!=null && this.getEmployeeLastUpdated().equals(castOther.getEmployeeLastUpdated()) ) )
 && ( (this.getCcgrjbLastUpdated()==castOther.getCcgrjbLastUpdated()) || ( this.getCcgrjbLastUpdated()!=null && castOther.getCcgrjbLastUpdated()!=null && this.getCcgrjbLastUpdated().equals(castOther.getCcgrjbLastUpdated()) ) )
 && ( (this.getJobCode()==castOther.getJobCode()) || ( this.getJobCode()!=null && castOther.getJobCode()!=null && this.getJobCode().equals(castOther.getJobCode()) ) )
 && ( (this.getLineMgrId()==castOther.getLineMgrId()) || ( this.getLineMgrId()!=null && castOther.getLineMgrId()!=null && this.getLineMgrId().equals(castOther.getLineMgrId()) ) )
 && ( (this.getCardNumber()==castOther.getCardNumber()) || ( this.getCardNumber()!=null && castOther.getCardNumber()!=null && this.getCardNumber().equals(castOther.getCardNumber()) ) )
 && ( (this.getIssueDate()==castOther.getIssueDate()) || ( this.getIssueDate()!=null && castOther.getIssueDate()!=null && this.getIssueDate().equals(castOther.getIssueDate()) ) )
 && ( (this.getExpiryDate()==castOther.getExpiryDate()) || ( this.getExpiryDate()!=null && castOther.getExpiryDate()!=null && this.getExpiryDate().equals(castOther.getExpiryDate()) ) )
 && ( (this.getBlockedDate()==castOther.getBlockedDate()) || ( this.getBlockedDate()!=null && castOther.getBlockedDate()!=null && this.getBlockedDate().equals(castOther.getBlockedDate()) ) )
 && ( (this.getProcessedType()==castOther.getProcessedType()) || ( this.getProcessedType()!=null && castOther.getProcessedType()!=null && this.getProcessedType().equals(castOther.getProcessedType()) ) )
 && ( (this.getProcessedDate()==castOther.getProcessedDate()) || ( this.getProcessedDate()!=null && castOther.getProcessedDate()!=null && this.getProcessedDate().equals(castOther.getProcessedDate()) ) )
 && ( (this.getCardTypeId()==castOther.getCardTypeId()) || ( this.getCardTypeId()!=null && castOther.getCardTypeId()!=null && this.getCardTypeId().equals(castOther.getCardTypeId()) ) )
 && ( (this.getEmpcardIsMaxxessUpdated()==castOther.getEmpcardIsMaxxessUpdated()) || ( this.getEmpcardIsMaxxessUpdated()!=null && castOther.getEmpcardIsMaxxessUpdated()!=null && this.getEmpcardIsMaxxessUpdated().equals(castOther.getEmpcardIsMaxxessUpdated()) ) )
 && ( (this.getEmpaccessIsMaxxessUpdated()==castOther.getEmpaccessIsMaxxessUpdated()) || ( this.getEmpaccessIsMaxxessUpdated()!=null && castOther.getEmpaccessIsMaxxessUpdated()!=null && this.getEmpaccessIsMaxxessUpdated().equals(castOther.getEmpaccessIsMaxxessUpdated()) ) )
 && ( (this.getCostcenterIsActive()==castOther.getCostcenterIsActive()) || ( this.getCostcenterIsActive()!=null && castOther.getCostcenterIsActive()!=null && this.getCostcenterIsActive().equals(castOther.getCostcenterIsActive()) ) )
 && ( (this.getEmpIsMaxxessUpdated()==castOther.getEmpIsMaxxessUpdated()) || ( this.getEmpIsMaxxessUpdated()!=null && castOther.getEmpIsMaxxessUpdated()!=null && this.getEmpIsMaxxessUpdated().equals(castOther.getEmpIsMaxxessUpdated()) ) )
 && ( (this.getCardIsActive()==castOther.getCardIsActive()) || ( this.getCardIsActive()!=null && castOther.getCardIsActive()!=null && this.getCardIsActive().equals(castOther.getCardIsActive()) ) )
 && ( (this.getAdbSubject()==castOther.getAdbSubject()) || ( this.getAdbSubject()!=null && castOther.getAdbSubject()!=null && this.getAdbSubject().equals(castOther.getAdbSubject()) ) )
 && ( (this.getAdbSequence()==castOther.getAdbSequence()) || ( this.getAdbSequence()!=null && castOther.getAdbSequence()!=null && this.getAdbSequence().equals(castOther.getAdbSequence()) ) )
 && ( (this.getAdbSetSequence()==castOther.getAdbSetSequence()) || ( this.getAdbSetSequence()!=null && castOther.getAdbSetSequence()!=null && this.getAdbSetSequence().equals(castOther.getAdbSetSequence()) ) )
 && ( (this.getAdbTimestamp()==castOther.getAdbTimestamp()) || ( this.getAdbTimestamp()!=null && castOther.getAdbTimestamp()!=null && this.getAdbTimestamp().equals(castOther.getAdbTimestamp()) ) )
 && ( (this.getAdbOpcode()==castOther.getAdbOpcode()) || ( this.getAdbOpcode()!=null && castOther.getAdbOpcode()!=null && this.getAdbOpcode().equals(castOther.getAdbOpcode()) ) )
 && ( (this.getAdbUpdateAll()==castOther.getAdbUpdateAll()) || ( this.getAdbUpdateAll()!=null && castOther.getAdbUpdateAll()!=null && this.getAdbUpdateAll().equals(castOther.getAdbUpdateAll()) ) )
 && ( (this.getAdbRefObject()==castOther.getAdbRefObject()) || ( this.getAdbRefObject()!=null && castOther.getAdbRefObject()!=null && this.getAdbRefObject().equals(castOther.getAdbRefObject()) ) )
 && ( (this.getAdbLDeliveryStatus()==castOther.getAdbLDeliveryStatus()) || ( this.getAdbLDeliveryStatus()!=null && castOther.getAdbLDeliveryStatus()!=null && this.getAdbLDeliveryStatus().equals(castOther.getAdbLDeliveryStatus()) ) )
 && ( (this.getAdbLCmsequence()==castOther.getAdbLCmsequence()) || ( this.getAdbLCmsequence()!=null && castOther.getAdbLCmsequence()!=null && this.getAdbLCmsequence().equals(castOther.getAdbLCmsequence()) ) )
 && ( (this.getAdbTrackingid()==castOther.getAdbTrackingid()) || ( this.getAdbTrackingid()!=null && castOther.getAdbTrackingid()!=null && this.getAdbTrackingid().equals(castOther.getAdbTrackingid()) ) )
 && ( (this.getAnprVehicleplate1()==castOther.getAnprVehicleplate1()) || ( this.getAnprVehicleplate1()!=null && castOther.getAnprVehicleplate1()!=null && this.getAnprVehicleplate1().equals(castOther.getAnprVehicleplate1()) ) )
 && ( (this.getAnprVehiclemodel1()==castOther.getAnprVehiclemodel1()) || ( this.getAnprVehiclemodel1()!=null && castOther.getAnprVehiclemodel1()!=null && this.getAnprVehiclemodel1().equals(castOther.getAnprVehiclemodel1()) ) )
 && ( (this.getAnprVehiclecolor1()==castOther.getAnprVehiclecolor1()) || ( this.getAnprVehiclecolor1()!=null && castOther.getAnprVehiclecolor1()!=null && this.getAnprVehiclecolor1().equals(castOther.getAnprVehiclecolor1()) ) )
 && ( (this.getAnprVehicleplate2()==castOther.getAnprVehicleplate2()) || ( this.getAnprVehicleplate2()!=null && castOther.getAnprVehicleplate2()!=null && this.getAnprVehicleplate2().equals(castOther.getAnprVehicleplate2()) ) )
 && ( (this.getAnprVehiclemodel2()==castOther.getAnprVehiclemodel2()) || ( this.getAnprVehiclemodel2()!=null && castOther.getAnprVehiclemodel2()!=null && this.getAnprVehiclemodel2().equals(castOther.getAnprVehiclemodel2()) ) )
 && ( (this.getAnprVehiclecolor2()==castOther.getAnprVehiclecolor2()) || ( this.getAnprVehiclecolor2()!=null && castOther.getAnprVehiclecolor2()!=null && this.getAnprVehiclecolor2().equals(castOther.getAnprVehiclecolor2()) ) )
 && ( (this.getAnprVehicleplate3()==castOther.getAnprVehicleplate3()) || ( this.getAnprVehicleplate3()!=null && castOther.getAnprVehicleplate3()!=null && this.getAnprVehicleplate3().equals(castOther.getAnprVehicleplate3()) ) )
 && ( (this.getAnprVehiclemodel3()==castOther.getAnprVehiclemodel3()) || ( this.getAnprVehiclemodel3()!=null && castOther.getAnprVehiclemodel3()!=null && this.getAnprVehiclemodel3().equals(castOther.getAnprVehiclemodel3()) ) )
 && ( (this.getAnprVehiclecolor3()==castOther.getAnprVehiclecolor3()) || ( this.getAnprVehiclecolor3()!=null && castOther.getAnprVehiclecolor3()!=null && this.getAnprVehiclecolor3().equals(castOther.getAnprVehiclecolor3()) ) )
 && ( (this.getEmpCarparkIsMaxxessUpdated()==castOther.getEmpCarparkIsMaxxessUpdated()) || ( this.getEmpCarparkIsMaxxessUpdated()!=null && castOther.getEmpCarparkIsMaxxessUpdated()!=null && this.getEmpCarparkIsMaxxessUpdated().equals(castOther.getEmpCarparkIsMaxxessUpdated()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode() );
         result = 37 * result + ( getCostcenterCode() == null ? 0 : this.getCostcenterCode().hashCode() );
         result = 37 * result + ( getGradeCode() == null ? 0 : this.getGradeCode().hashCode() );
         result = 37 * result + ( getEmployeeName() == null ? 0 : this.getEmployeeName().hashCode() );
         result = 37 * result + ( getUpdateComment() == null ? 0 : this.getUpdateComment().hashCode() );
         result = 37 * result + ( getLastUpdated() == null ? 0 : this.getLastUpdated().hashCode() );
         result = 37 * result + ( getIsActive() == null ? 0 : this.getIsActive().hashCode() );
         result = 37 * result + ( getEmployeeType() == null ? 0 : this.getEmployeeType().hashCode() );
         result = 37 * result + ( getContactDetail() == null ? 0 : this.getContactDetail().hashCode() );
         result = 37 * result + ( getFirstName() == null ? 0 : this.getFirstName().hashCode() );
         result = 37 * result + ( getMiddleName() == null ? 0 : this.getMiddleName().hashCode() );
         result = 37 * result + ( getLastName() == null ? 0 : this.getLastName().hashCode() );
         result = 37 * result + ( getInsertedDate() == null ? 0 : this.getInsertedDate().hashCode() );
         result = 37 * result + ( getMaxxessId() == null ? 0 : this.getMaxxessId().hashCode() );
         result = 37 * result + ( getEmployeeLastUpdated() == null ? 0 : this.getEmployeeLastUpdated().hashCode() );
         result = 37 * result + ( getCcgrjbLastUpdated() == null ? 0 : this.getCcgrjbLastUpdated().hashCode() );
         result = 37 * result + ( getJobCode() == null ? 0 : this.getJobCode().hashCode() );
         result = 37 * result + ( getLineMgrId() == null ? 0 : this.getLineMgrId().hashCode() );
         result = 37 * result + ( getCardNumber() == null ? 0 : this.getCardNumber().hashCode() );
         result = 37 * result + ( getIssueDate() == null ? 0 : this.getIssueDate().hashCode() );
         result = 37 * result + ( getExpiryDate() == null ? 0 : this.getExpiryDate().hashCode() );
         result = 37 * result + ( getBlockedDate() == null ? 0 : this.getBlockedDate().hashCode() );
         result = 37 * result + ( getProcessedType() == null ? 0 : this.getProcessedType().hashCode() );
         result = 37 * result + ( getProcessedDate() == null ? 0 : this.getProcessedDate().hashCode() );
         result = 37 * result + ( getCardTypeId() == null ? 0 : this.getCardTypeId().hashCode() );
         result = 37 * result + ( getEmpcardIsMaxxessUpdated() == null ? 0 : this.getEmpcardIsMaxxessUpdated().hashCode() );
         result = 37 * result + ( getEmpaccessIsMaxxessUpdated() == null ? 0 : this.getEmpaccessIsMaxxessUpdated().hashCode() );
         result = 37 * result + ( getCostcenterIsActive() == null ? 0 : this.getCostcenterIsActive().hashCode() );
         result = 37 * result + ( getEmpIsMaxxessUpdated() == null ? 0 : this.getEmpIsMaxxessUpdated().hashCode() );
         result = 37 * result + ( getCardIsActive() == null ? 0 : this.getCardIsActive().hashCode() );
         result = 37 * result + ( getAdbSubject() == null ? 0 : this.getAdbSubject().hashCode() );
         result = 37 * result + ( getAdbSequence() == null ? 0 : this.getAdbSequence().hashCode() );
         result = 37 * result + ( getAdbSetSequence() == null ? 0 : this.getAdbSetSequence().hashCode() );
         result = 37 * result + ( getAdbTimestamp() == null ? 0 : this.getAdbTimestamp().hashCode() );
         result = 37 * result + ( getAdbOpcode() == null ? 0 : this.getAdbOpcode().hashCode() );
         result = 37 * result + ( getAdbUpdateAll() == null ? 0 : this.getAdbUpdateAll().hashCode() );
         result = 37 * result + ( getAdbRefObject() == null ? 0 : this.getAdbRefObject().hashCode() );
         result = 37 * result + ( getAdbLDeliveryStatus() == null ? 0 : this.getAdbLDeliveryStatus().hashCode() );
         result = 37 * result + ( getAdbLCmsequence() == null ? 0 : this.getAdbLCmsequence().hashCode() );
         result = 37 * result + ( getAdbTrackingid() == null ? 0 : this.getAdbTrackingid().hashCode() );
         result = 37 * result + ( getAnprVehicleplate1() == null ? 0 : this.getAnprVehicleplate1().hashCode() );
         result = 37 * result + ( getAnprVehiclemodel1() == null ? 0 : this.getAnprVehiclemodel1().hashCode() );
         result = 37 * result + ( getAnprVehiclecolor1() == null ? 0 : this.getAnprVehiclecolor1().hashCode() );
         result = 37 * result + ( getAnprVehicleplate2() == null ? 0 : this.getAnprVehicleplate2().hashCode() );
         result = 37 * result + ( getAnprVehiclemodel2() == null ? 0 : this.getAnprVehiclemodel2().hashCode() );
         result = 37 * result + ( getAnprVehiclecolor2() == null ? 0 : this.getAnprVehiclecolor2().hashCode() );
         result = 37 * result + ( getAnprVehicleplate3() == null ? 0 : this.getAnprVehicleplate3().hashCode() );
         result = 37 * result + ( getAnprVehiclemodel3() == null ? 0 : this.getAnprVehiclemodel3().hashCode() );
         result = 37 * result + ( getAnprVehiclecolor3() == null ? 0 : this.getAnprVehiclecolor3().hashCode() );
         result = 37 * result + ( getEmpCarparkIsMaxxessUpdated() == null ? 0 : this.getEmpCarparkIsMaxxessUpdated().hashCode() );
         return result;
   }   


}


