package com.solace.connector.db.pull.entity;
// Generated 19-Sep-2023, 11:35:03 am by Hibernate Tools 5.6.2.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VchsIClacFinTransaction generated by hbm2java
 */
@Entity
@Table(name="VCHS_I_CLAC_FIN_TRANSACTION"
    
)
public class VchsIClacFinTransaction  implements java.io.Serializable {


     private BigDecimal vchsICftId;
     private VchsIClacCustInvoice vchsIClacCustInvoice;
     private String txnDesc;
     private String chgCode;
     private BigDecimal amtBc;
     private BigDecimal amtFc;
     private String baseCurrCode;
     private BigDecimal xchgRate;
     private String forCurrCode;
     private String pmntForm;
     private String pmntMode;
     private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;
     private String processStatus;
     private Date processDate;
     private BigDecimal clacFtnId;

    public VchsIClacFinTransaction() {
    }

	
    public VchsIClacFinTransaction(BigDecimal vchsICftId) {
        this.vchsICftId = vchsICftId;
    }
    public VchsIClacFinTransaction(BigDecimal vchsICftId, VchsIClacCustInvoice vchsIClacCustInvoice, String txnDesc, String chgCode, BigDecimal amtBc, BigDecimal amtFc, String baseCurrCode, BigDecimal xchgRate, String forCurrCode, String pmntForm, String pmntMode, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate, String processStatus, Date processDate, BigDecimal clacFtnId) {
       this.vchsICftId = vchsICftId;
       this.vchsIClacCustInvoice = vchsIClacCustInvoice;
       this.txnDesc = txnDesc;
       this.chgCode = chgCode;
       this.amtBc = amtBc;
       this.amtFc = amtFc;
       this.baseCurrCode = baseCurrCode;
       this.xchgRate = xchgRate;
       this.forCurrCode = forCurrCode;
       this.pmntForm = pmntForm;
       this.pmntMode = pmntMode;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.processStatus = processStatus;
       this.processDate = processDate;
       this.clacFtnId = clacFtnId;
    }
   
     @Id 

    
    @Column(name="VCHS_I_CFT_ID", unique=true, nullable=false, precision=15, scale=0)
    public BigDecimal getVchsICftId() {
        return this.vchsICftId;
    }
    
    public void setVchsICftId(BigDecimal vchsICftId) {
        this.vchsICftId = vchsICftId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VCHS_I_CCI_ID")
    public VchsIClacCustInvoice getVchsIClacCustInvoice() {
        return this.vchsIClacCustInvoice;
    }
    
    public void setVchsIClacCustInvoice(VchsIClacCustInvoice vchsIClacCustInvoice) {
        this.vchsIClacCustInvoice = vchsIClacCustInvoice;
    }

    
    @Column(name="TXN_DESC", length=100)
    public String getTxnDesc() {
        return this.txnDesc;
    }
    
    public void setTxnDesc(String txnDesc) {
        this.txnDesc = txnDesc;
    }

    
    @Column(name="CHG_CODE", length=5)
    public String getChgCode() {
        return this.chgCode;
    }
    
    public void setChgCode(String chgCode) {
        this.chgCode = chgCode;
    }

    
    @Column(name="AMT_BC", precision=15, scale=3)
    public BigDecimal getAmtBc() {
        return this.amtBc;
    }
    
    public void setAmtBc(BigDecimal amtBc) {
        this.amtBc = amtBc;
    }

    
    @Column(name="AMT_FC", precision=15, scale=3)
    public BigDecimal getAmtFc() {
        return this.amtFc;
    }
    
    public void setAmtFc(BigDecimal amtFc) {
        this.amtFc = amtFc;
    }

    
    @Column(name="BASE_CURR_CODE", length=5)
    public String getBaseCurrCode() {
        return this.baseCurrCode;
    }
    
    public void setBaseCurrCode(String baseCurrCode) {
        this.baseCurrCode = baseCurrCode;
    }

    
    @Column(name="XCHG_RATE", precision=15, scale=3)
    public BigDecimal getXchgRate() {
        return this.xchgRate;
    }
    
    public void setXchgRate(BigDecimal xchgRate) {
        this.xchgRate = xchgRate;
    }

    
    @Column(name="FOR_CURR_CODE", length=5)
    public String getForCurrCode() {
        return this.forCurrCode;
    }
    
    public void setForCurrCode(String forCurrCode) {
        this.forCurrCode = forCurrCode;
    }

    
    @Column(name="PMNT_FORM", length=15)
    public String getPmntForm() {
        return this.pmntForm;
    }
    
    public void setPmntForm(String pmntForm) {
        this.pmntForm = pmntForm;
    }

    
    @Column(name="PMNT_MODE", length=15)
    public String getPmntMode() {
        return this.pmntMode;
    }
    
    public void setPmntMode(String pmntMode) {
        this.pmntMode = pmntMode;
    }

    
    @Column(name="CREATED_BY", length=30)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="CREATED_DATE", length=11)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="MODIFIED_BY", length=30)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    
    @Column(name="MODIFIED_DATE", length=11)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="PROCESS_STATUS", length=1)
    public String getProcessStatus() {
        return this.processStatus;
    }
    
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus;
    }

    
    @Column(name="PROCESS_DATE", length=11)
    public Date getProcessDate() {
        return this.processDate;
    }
    
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }

    
    @Column(name="CLAC_FTN_ID", precision=15, scale=0)
    public BigDecimal getClacFtnId() {
        return this.clacFtnId;
    }
    
    public void setClacFtnId(BigDecimal clacFtnId) {
        this.clacFtnId = clacFtnId;
    }




}


