package com.solace.connector.db.pull.entity;
// Generated 11-Apr-2023, 10:51:41 am by Hibernate Tools 5.6.2.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
import java.util.Date;
import java.sql.Blob;
import java.sql.Clob;
@Entity
@Table(name="CUSTOMER"
    
)
public class Customer  implements java.io.Serializable {


private Integer customerId;
private String adbTrackingid;
private String DStatus;
private String sequenceId;
private String city;
private String firstName;
private String lastName;
private String state;
private Date dbtime;
private Blob blobc;
private Clob clobc;
private Date systemtime;
     private CustomerId id;

    public Customer() {
    }

    public Customer(CustomerId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
@AttributeOverride(name="zip", column=@Column(name="ZIP") )
} )
    public CustomerId getId() {
        return this.id;
    }
    
    public void setId(CustomerId id) {
        this.id = id;
    }




    @Column(name="CUSTOMER_ID", nullable=false, precision=10, scale=0)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    @Column(name="ADB_TRACKINGID")
    public String getAdbTrackingid() {
        return this.adbTrackingid;
    }
    
    public void setAdbTrackingid(String adbTrackingid) {
        this.adbTrackingid = adbTrackingid;
    }
    @Column(name="D_STATUS", length=5)
    public String getDStatus() {
        return this.DStatus;
    }
    
    public void setDStatus(String DStatus) {
        this.DStatus = DStatus;
    }
    @Column(name="SEQUENCE_ID", length=50)
    public String getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(String sequenceId) {
        this.sequenceId = sequenceId;
    }
    @Column(name="CITY")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    @Column(name="FIRST_NAME")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    @Column(name="LAST_NAME")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    @Column(name="STATE")
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    @Column(name="DBTIME", length=11)
    public Date getDbtime() {
        return this.dbtime;
    }
    
    public void setDbtime(Date dbtime) {
        this.dbtime = dbtime;
    }
    @Column(name="BLOBC")
    public Blob getBlobc() {
        return this.blobc;
    }
    
    public void setBlobc(Blob blobc) {
        this.blobc = blobc;
    }
    @Column(name="CLOBC")
    public Clob getClobc() {
        return this.clobc;
    }
    
    public void setClobc(Clob clobc) {
        this.clobc = clobc;
    }
    @Column(name="SYSTEMTIME", length=11)
    public Date getSystemtime() {
        return this.systemtime;
    }
    
    public void setSystemtime(Date systemtime) {
        this.systemtime = systemtime;
    }
}


