package com.solace.connector.db.pull.entity;
// Generated 11-Apr-2023, 10:51:41 am by Hibernate Tools 5.6.2.Final


import java.sql.Blob;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerId generated by hbm2java
 */
@Embeddable
public class CustomerId  implements java.io.Serializable {


     private String zip;

    public CustomerId() {
    }

	
    public CustomerId(Integer customerId) {
        this.customerId = customerId;
    }










    @Column(name="ZIP")
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }






   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustomerId) ) return false;
		 CustomerId castOther = ( CustomerId ) other; 
         
return
 ( (this.getZip()==castOther.getZip()) || ( this.getZip()!=null && castOther.getZip()!=null && this.getZip().equals(castOther.getZip()) ) )
;
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getZip() == null ? 0 : this.getZip().hashCode() );
         return result;
   }   


}


