package com.solace.connector.db.pull.entity;
// Generated 31-Mar-2023, 1:48:21 pm by Hibernate Tools 5.6.2.Final


import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SourcePassengerId generated by hbm2java
 */
@Embeddable
public class SourcePassengerId  implements java.io.Serializable {


     private String flag;

    public SourcePassengerId() {
    }

	
    public SourcePassengerId(Integer passengerId) {
        this.passengerId = passengerId;
    }











    @Column(name="FLAG")
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }




   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SourcePassengerId) ) return false;
		 SourcePassengerId castOther = ( SourcePassengerId ) other; 
         
return
 ( (this.getFlag()==castOther.getFlag()) || ( this.getFlag()!=null && castOther.getFlag()!=null && this.getFlag().equals(castOther.getFlag()) ) )
;
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFlag() == null ? 0 : this.getFlag().hashCode() );
         return result;
   }   


}


