package com.solace.connector.db.pull.entity;
// Generated 31-Mar-2023, 1:48:21 pm by Hibernate Tools 5.6.2.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SourcePassenger generated by hbm2java
 */
import java.util.Date;
import java.sql.Blob;
import com.fasterxml.jackson.annotation.JsonIgnore;
import javax.persistence.*;
import java.util.Map;
import java.util.List;
@Entity
@Table(name="SOURCE_PASSENGER"
    
)
public class SourcePassenger  implements java.io.Serializable {


private Integer passengerId;
private String dbtrackid;
private Date readtime;
private String address;
private Date birthday;
private Blob blobc;
private String clobc;
private String contactNo;
private Date createdAt;
private String name;
private String nationality;
private List<Map> messageLoadCol;
     private SourcePassengerId id;

    public SourcePassenger() {
    }

    public SourcePassenger(SourcePassengerId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
@AttributeOverride(name="flag", column=@Column(name="FLAG") )
} )
    public SourcePassengerId getId() {
        return this.id;
    }
    
    public void setId(SourcePassengerId id) {
        this.id = id;
    }




    @Column(name="PASSENGER_ID", nullable=false, precision=10, scale=0)
    public Integer getPassengerId() {
        return this.passengerId;
    }
    
    public void setPassengerId(Integer passengerId) {
        this.passengerId = passengerId;
    }
    @Column(name="DBTRACKID")
    public String getDbtrackid() {
        return this.dbtrackid;
    }
    
    public void setDbtrackid(String dbtrackid) {
        this.dbtrackid = dbtrackid;
    }
    @Column(name="READTIME", length=11)
    public Date getReadtime() {
        return this.readtime;
    }
    
    public void setReadtime(Date readtime) {
        this.readtime = readtime;
    }
    @Column(name="ADDRESS")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    @Column(name="BIRTHDAY", length=11)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    @Column(name="BLOBC")
    public Blob getBlobc() {
        return this.blobc;
    }
    
    public void setBlobc(Blob blobc) {
        this.blobc = blobc;
    }
    @Column(name="CLOBC")
    public String getClobc() {
        return this.clobc;
    }
    
    public void setClobc(String clobc) {
        this.clobc = clobc;
    }
    @Column(name="CONTACT_NO")
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    @Column(name="CREATED_AT", length=11)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column(name="NATIONALITY")
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }


    @JsonIgnore
    @Transient
    public List<Map> getMessageLoadCol() {
        return messageLoadCol;
    }
    public void setMessageLoadCol(List<Map> messageLoadCol) {
        this.messageLoadCol = messageLoadCol;
    }
}


