package com.solace.connector.db.pull.entity;
// Generated 31-Mar-2023, 1:48:21 pm by Hibernate Tools 5.6.2.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name="STUDENTS"
    
)
public class Students  implements java.io.Serializable {


     private Integer stdId;
     private String stdName;
     private Employee employee;

    public Students() {
    }

	
    public Students(Integer stdId, String stdName) {
        this.stdId = stdId;
        this.stdName = stdName;
    }
    public Students(Integer stdId, String stdName, Employee employee) {
       this.stdId = stdId;
       this.stdName = stdName;
       this.employee = employee;
    }
   
     @Id 

    
    @Column(name="STD_ID", unique=true, nullable=false, precision=22, scale=0)
    public Integer getStdId() {
        return this.stdId;
    }
    
    public void setStdId(Integer stdId) {
        this.stdId = stdId;
    }

    
    @Column(name="STD_NAME", nullable=false, length=50)
    public String getStdName() {
        return this.stdName;
    }
    
    public void setStdName(String stdName) {
        this.stdName = stdName;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="students")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }




}


