# ----------------------------------------------------
# INTERNAL CONNECTOR CONFIGURATION
# For Connector Developer use only
# ----------------------------------------------------

spring:
  cloud:
    function:
      # [INTERNAL] Message handler function definitions
      definition: "\
        setupWorkflow_0|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck;\
        setupWorkflow_1|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck;\
        setupWorkflow_2|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck;\
        setupWorkflow_3|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck;\
        setupWorkflow_4|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck;\
        setupWorkflow_5|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck;\
        setupWorkflow_6|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck;\
        setupWorkflow_7|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck;\
        setupWorkflow_8|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck;\
        setupWorkflow_9|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck"

    stream:

      # [INTERNAL] Descriptive Binding Names (Aliases)
      function:
        bindings:
          setupWorkflow_0|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck-in-0: input-0
          setupWorkflow_1|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck-in-0: input-1
          setupWorkflow_2|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck-in-0: input-2
          setupWorkflow_3|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck-in-0: input-3
          setupWorkflow_4|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck-in-0: input-4
          setupWorkflow_5|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck-in-0: input-5
          setupWorkflow_6|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck-in-0: input-6
          setupWorkflow_7|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck-in-0: input-7
          setupWorkflow_8|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck-in-0: input-8
          setupWorkflow_9|mapHeaders|transformHeaders|dataCollectingParellel|sendAndResolveAck-in-0: input-9
          output_0-out-0: output-0
          output_1-out-0: output-1
          output_2-out-0: output-2
          output_3-out-0: output-3
          output_4-out-0: output-4
          output_5-out-0: output-5
          output_6-out-0: output-6
          output_7-out-0: output-7
          output_8-out-0: output-8
          output_9-out-0: output-9


      # [INTERNAL]  Pre-create output bindings
      output-bindings: "\
        output_0;\
        output_1;\
        output_2;\
        output_3;\
        output_4;\
        output_5;\
        output_6;\
        output_7;\
        output_8;\
        output_9"


      default-binder: undefined

      # Default Binding Configuration
      default:
        consumer:
          # [INTERNAL] Auto-startup must always be disabled
          auto-startup: false
        producer:
          # [INTERNAL] Auto-startup must always be disabled
          auto-startup: false
          # [INTERNAL] Producer error channels must always be enabled
          error-channel-enabled: true
          # [INTERNAL] Allows greater outbound message type flexibility
          use-native-encoding: true

      # Assign dummy consumer groups
      bindings:
        input-0:
          group: group-0
        input-1:
          group: group-1
        input-2:
          group: group-2
        input-3:
          group: group-3
        input-4:
          group: group-4
        input-5:
          group: group-5
        input-6:
          group: group-6
        input-7:
          group: group-7
        input-8:
          group: group-8
        input-9:
          group: group-9
      solace:
        default:
          consumer:
            add-destination-as-subscription-to-queue: false
            provision-durable-queue: false
            provision-error-queue: false
            queue-name-expression: "destination"

solace:
  connector:
    workflows:
      # [INTERNAL] Link/Route workflow to consumer/producer bindings
      0:
        input-bindings:
          - input-0
        output-bindings:
          - output-0
      1:
        input-bindings:
          - input-1
        output-bindings:
          - output-1
      2:
        input-bindings:
          - input-2
        output-bindings:
          - output-2
      3:
        input-bindings:
          - input-3
        output-bindings:
          - output-3
      4:
        input-bindings:
          - input-4
        output-bindings:
          - output-4
      5:
        input-bindings:
          - input-5
        output-bindings:
          - output-5
      6:
        input-bindings:
          - input-6
        output-bindings:
          - output-6
      7:
        input-bindings:
          - input-7
        output-bindings:
          - output-7
      8:
        input-bindings:
          - input-8
        output-bindings:
          - output-8
      9:
        input-bindings:
          - input-9
        output-bindings:
          - output-9


    security:
      enabled: false # Remove when support for security config is added
      endpoint-access:
        custom-filters:
          default-admin:
            matcher:
              mode: management_request
              method: POST
            access:
              roles:
                - admin

logging:
  level:
    root: warn

# Spring Management Configuration
management:
  health:
    # The JMS Binder health indicator is used instead
    jms:
      enabled: false
  metrics:
    export:
      defaults:
        enabled: false
  endpoints:
    web:
      exposure:
        include: "health,leaderelection"

  endpoint:
    prometheus:
      enabled: false
    health:
      status:
        # Change default order so that RECONNECTING takes precedence over UP and UNKNOWN
        order:
          - DOWN
          - OUT_OF_SERVICE
          - RECONNECTING
          - UP
          - UNKNOWN