spring:
  boot:
    admin:
      client:
        enabled: true
        url: 'http://localhost:8082'
        auto-registration: true
        instance:
          name: DataBase(Source)
          service-url: 'http://localhost:${server.port}'
    application:
      name: DataBase(Source)
  cloud:
    stream:
      bindings:
        input-0:
          destination: ""
          binder: solace-db
          group: no
        output-0:
          destination: lvq/source_passenger
          binder: solace
          content-type: application/x-java-serialized-object
    config:
      import-check:
        enabled: false
solace:
  connector:
    workflows:
      '0':
        enabled: true
      '1':
        enabled: false
    management:
      leader-election:
        mode: active_standby
        fail-over:
          max-attempts: 3
          back-off-initial-interval: 1000
          back-off-max-interval: 10000
          back-off-multiplier: 2
      queue: ""
      session:
        host: d
        msgVpn: d
        clientUsername: d
        clientPassword: d
    security:
      enabled: false
  java:
    host: d
    msgVpn: d
    clientUsername: d
    clientPassword: d
    connect-retries: -1
    reconnect-retries: -1
    apiProperties:
      pub_ack_window_size: 50
      pub_ack_time: 200
management:
  metrics:
    export:
      simple:
        enabled: true
    logfile:
      external-file: log/connector/runtime.log
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: 'health,metrics,loggers,logfile,channels,env,workflows,leaderelection,bindings'
        exclude: 'diskSpace,mappings'
server:
  port: 8092
logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    com.solace.spring.cloud.stream.binders.db: INFO
    com.solace.spring: ERROR
    org.springframework: ERROR
    org.springframework.context.support.DefaultLifecycleProcessor: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.solace.spring.cloud.stream.binders.db.jdbc.DatabaseUtil: ERROR
jasypt:
  encryptor:
    password: test123@!
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
solace-persistence:
  datasource:
    url: 'jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))(CONNECT_DATA =(SERVICE_NAME= ORCL)))'
    username: CM_SCHEMA
    password: demo
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 5000
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_updates: true
        order_inserts: true
        generate_statistics: false
        dialect: org.hibernate.dialect.Oracle10gDialect
    database: oracle
  source:
    sendBatchSize: 1
    queryMax: 100
    maxDbRetry: 3
    triggerInterval: 2000
    retryInterval: 10
    enableRetry: true
    retryCount: 3
    enableBufferedJpaBatch: true
    bufferWaitSeconds: 5
    enableTrackingId: true
    enableDatabaseTimestamp: true
    enableConnectorTimestamp: true
    enableBenchmarkInfo: true
