package com.solace.connectors.database.sink.entity;
// Generated Dec 18, 2022 5:04:44 PM by Hibernate Tools 5.6.2.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="ADDRESS"
)
public class Address  implements java.io.Serializable {


     private BigDecimal addressId;
     private String city;
     private Date createDate;
     private BigDecimal customerNumber;
     private String state;
     private String street;
     private String zip;

    public Address() {
    }

	
    public Address(BigDecimal addressId) {
        this.addressId = addressId;
    }
    public Address(BigDecimal addressId, String city, Date createDate, BigDecimal customerNumber, String state, String street, String zip) {
       this.addressId = addressId;
       this.city = city;
       this.createDate = createDate;
       this.customerNumber = customerNumber;
       this.state = state;
       this.street = street;
       this.zip = zip;
    }
   
     @Id 

    
    @Column(name="ADDRESS_ID", unique=true, nullable=false, precision=10, scale=0)
    public BigDecimal getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(BigDecimal addressId) {
        this.addressId = addressId;
    }

    
    @Column(name="CITY")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="CREATE_DATE", length=11)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CUSTOMER_NUMBER", precision=10, scale=0)
    public BigDecimal getCustomerNumber() {
        return this.customerNumber;
    }
    
    public void setCustomerNumber(BigDecimal customerNumber) {
        this.customerNumber = customerNumber;
    }

    
    @Column(name="STATE")
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="STREET")
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="ZIP")
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }




}


