package com.solace.connectors.database.sink.entity;
// Generated Dec 18, 2022 5:04:44 PM by Hibernate Tools 5.6.2.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER"
)
public class Customer  implements java.io.Serializable {


     private Long customerId;
     private String adbTrackingid;
     private String DStatus;
     private String sequenceId;
     private String city;
     private String firstName;
     private String lastName;
     private String state;
     private String zip;
     private Date dbtime;
     private Byte[] blobc;
     private String clobc;
     private Date systemtime;

    public Customer() {
    }

	
    public Customer(Long customerId) {
        this.customerId = customerId;
    }
    public Customer(Long customerId, String adbTrackingid, String DStatus, String sequenceId, String city, String firstName, String lastName, String state, String zip, Date dbtime, Byte[] blobc, String clobc, Date systemtime) {
       this.customerId = customerId;
       this.adbTrackingid = adbTrackingid;
       this.DStatus = DStatus;
       this.sequenceId = sequenceId;
       this.city = city;
       this.firstName = firstName;
       this.lastName = lastName;
       this.state = state;
       this.zip = zip;
       this.dbtime = dbtime;
       this.blobc = blobc;
       this.clobc = clobc;
       this.systemtime = systemtime;
    }
   
     @Id 

    
    @Column(name="CUSTOMER_ID", unique=true, nullable=false, precision=10, scale=0)
    public Long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="ADB_TRACKINGID")
    public String getAdbTrackingid() {
        return this.adbTrackingid;
    }
    
    public void setAdbTrackingid(String adbTrackingid) {
        this.adbTrackingid = adbTrackingid;
    }

    
    @Column(name="D_STATUS", length=5)
    public String getDStatus() {
        return this.DStatus;
    }
    
    public void setDStatus(String DStatus) {
        this.DStatus = DStatus;
    }

    
    @Column(name="SEQUENCE_ID", length=50)
    public String getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(String sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="CITY")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="FIRST_NAME")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="STATE")
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="ZIP")
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    
    @Column(name="DBTIME", length=11)
    public Date getDbtime() {
        return this.dbtime;
    }
    
    public void setDbtime(Date dbtime) {
        this.dbtime = dbtime;
    }

    
    @Column(name="BLOBC")
    public Byte[] getBlobc() {
        return this.blobc;
    }
    
    public void setBlobc(Byte[] blobc) {
        this.blobc = blobc;
    }

    
    @Column(name="CLOBC")
    public String getClobc() {
        return this.clobc;
    }
    
    public void setClobc(String clobc) {
        this.clobc = clobc;
    }

    
    @Column(name="SYSTEMTIME", length=11)
    public Date getSystemtime() {
        return this.systemtime;
    }
    
    public void setSystemtime(Date systemtime) {
        this.systemtime = systemtime;
    }




}


